### ISSUE TITLE
Where can find the such API info?

### ISSUE THREAD

**Issue by burntbear00** [tomwalder/php-gds#104]
define('GDS_APP_NAME', '');
define('GDS_KEY_FILE_PATH', '');
define('GDS_SERVICE_ACCOUNT_NAME', '');
define('GDS_DATASET_ID', '');

i tried
Project Name for  'GDS_APP_NAME' ,
service account .p12 file path for 'GDS_KEY_FILE_PATH' ,
service account name or email for 'GDS_SERVICE_ACCOUNT_NAME' ,
Google Project Id for 'GDS_DATASET_ID'
but also not work.

I am very frustrating for this. I wanna use this good library.
Please help us. Thank you.

**Comment by tomwalder** [comment]
Check this out!

https://github.com/tomwalder/php-gds/issues/79

**Comment by burntbear00** [comment]
Thank you for your reply.
Tried, also not work. Sad

**Comment by tomwalder** [comment]
OK, well it works for me & others...

Are you trying to use the "REMOTE" JSON service, or are you developing for AppEngine directly?

**Comment by burntbear00** [comment]
I am using Google Cloud Platform and build the php api at a nginx hosting. 
I already created a service account.
I tried using key.p12 / service.json  generated by google Api manager console.

**Comment by burntbear00** [comment]
is it support php 5.4?

**Comment by burntbear00** [comment]
solved problem, The reason is that my old version of php on Centos7.  Thank you so much.
This library is very wonderful.

**Comment by tomwalder** [comment]
No problem - glad it's useful!
