### ISSUE TITLE
Performance improvements with protocol buffer interface?

### ISSUE THREAD

**Issue by ajck** [tomwalder/php-gds#105]
Not an issue, but just wondering, what sort of performance improvements might we be looking at using the PHP-GDS 2.0 protocol buffer based interface rather than the JSON API interface, in real terms? i.e. would there be a significant noticeable difference do you think? Any real-world testimonies?!

Thanks.

**Comment by tomwalder** [comment]
In my experience - yes, it is significantly faster (and therefore cheaper too).

Are you running on AppEngine? If so, I would recommend the switch.

**Comment by ajck** [comment]
Yes on App Engine and using your great library. Just thinking that as my site scales I will be incurring significant costs from not being able to do projection or keys only queries so trying to think/find a way to achieve that optimisation. Just spent a while looking into protocol buffers (e.g. Google's docs) and how you're implementing them. I understand the gist of it all, and can see the generalities of how you're using them (e.g. in Gateway/ProtoBuf.php, Mapper/ProtoBuf.php & ProtoBufGQLParser.php) but don't understand well enough to fork and implement unfortunately! Other alternatives, like using the Google Client API PHP libs directly, look too complex and messy, I like all the advantages of your lib. Hoping a solution will turn up at some point!

By the way, I'm in Google's Cloud Insider programme and keep mentioning/recommending php-gds to the Cloud guys :) One of their product managers said he'll get their docs team to mention it in some docs or other...

**Comment by tomwalder** [comment]
Thanks for the vote of confidence ;)

There is a development branch (quite far along) for "Key Properties" which provides the foundation for Keys-only queries. I am fairly sure in maintains backwards compatibility too.

https://github.com/tomwalder/php-gds/tree/key-properties

**Comment by ajck** [comment]
Looks good - is it possible to do keys only queries with it yet, and if so how?

**Comment by tomwalder** [comment]
Closing this performance ticket.

See #42 for Keys-only queries
