### ISSUE TITLE
php-gds not compatible with google/apiclient 1.1.7 and above

### ISSUE THREAD

**Issue by CharmySoft** [tomwalder/php-gds#106]
This library is running fine with google/apiclient 1.1.6 but it is not compatible with the remote Google API client (google/apiclient) 1.1.7 and above. Some specifications on the README file or some other setup guide documentation might be helpful for people encountering troubles with the remote JSON or p12 key file API.

The default version using composer to require google/apiclient is 1.1.7 as of now (and dev 2.0.0 rc has been released as well), and this can cause problems for anyone who don't specify the version when use composer to require the library.

When use `createClientFromJson` or `createGoogleClient` instead of the native `ProtoBuf` gateway, the store object can be initialized with no problem, but any database operation later with the store would crash the PHP runtime, resulting a "CGI / FastCGUI has stopped working" error on the local development machine, as tested on Windows.

**Comment by martinojes** [comment]
I have a similar experience. I was trying to upgrade the library to dev v2.0.0 RC, running an app on GAE. 
That version of the library uses Guzzle 6 with cURL as default HTTP handler for the REST operations, but App Engine blocks cURL from doing requests to Google's own domains. I.e. it does not work.

Guzzle supports using a custom HTTP handler, and I tried to find or create one using Sockets instead of cURL, but without any proper documentation I didn't succeed.

I haven't tried 1.1.7, but maybe that version has the same problems as 2.0.0?

I worked around my problem by reverting to the older Google Client API (I'm using 1.1.5)

**Comment by CharmySoft** [comment]
![image](https://cloud.githubusercontent.com/assets/10954839/14223795/822b97b6-f87e-11e5-9894-ce8ce9434882.png)
OK. The "CGI / FastCGUI has stopped working" error I reported is not caused by the version 1.1.7, sorry about the mis-report. After some tests conducted with different versions, and I found out the error remains on 1.1.5 and 1.1.6 in my case. Though 2.0.0 is surely incompatible.

After running the PHPUnit test, it turned out everything runs OK on the command-line. All the tests were passes and OK. I even tried running `php [my_script.php]` and `php-cgi [my_script.php]` and it turned out just fine. I can get the fetch result. 
![image](https://cloud.githubusercontent.com/assets/10954839/14223770/d654171a-f87d-11e5-9a9d-35a2c73ad39c.png)

However, on Google App Engine, the script still crashes php-cgi each time it runs. The logs indicate a HTTP request status 500 error. 

```
INFO     2016-04-02 01:40:14,730 dispatcher.py:197] Starting module "default" running at: http://localhost:8000
INFO     2016-04-02 01:40:14,730 admin_server.py:116] Starting admin server at: http://localhost:8080
ERROR:root:php failure (-1073740791) with:

stdout:



INFO     2016-04-02 01:40:27,696 module.py:787] default: "GET /php/test.php HTTP/1.1" 500 -
```

My code is quite simple, a simple connect and fetch. Runs fine on commond-line, but gets errors on GAE environment. Any help with what the cause might be?

```
$obj_client = GDS\Gateway\GoogleAPIClient::createClientFromJson(GDS_JSON_KEY_FILE_PATH);
$obj_gateway = new GDS\Gateway\GoogleAPIClient($obj_client, GDS_DATASET_ID);
$obj_store = new \GDS\Store('App', $obj_gateway);
var_dump($obj_store->fetchAll());
```

**Comment by CharmySoft** [comment]
OK, I'm closing this issue, as the problem I'm experiencing is specific to my own local machine and is not reproducible so this is not helpful. Sorry about the mis-report on the original post.

**Comment by tomwalder** [comment]
No problem.

There is a dev branch of php-gds to support the upstream 2.0 series from Google. However, they keep changing things in the RC series, so I am waiting for release before fixing the unit tests.

https://github.com/tomwalder/php-gds/tree/google-api-two
