### ISSUE TITLE
Local GQL parser allows invalid syntax that does not work on the remote production server

### ISSUE THREAD

**Issue by CharmySoft** [tomwalder/php-gds#107]
Some invalid syntax that causes errors on the remote GAE environment can strangely work fine on the local dev environment. This can cause problems for debugging and make it difficult to trace down the errors because the syntax error is not reported on the local development server. 

Take the following GQL for example:
```SQL
SELECT * FROM store WHERE name=string
```
This works fine with the local GQL parser, whereas on [Google Cloud Datastore GQL reference](https://cloud.google.com/datastore/docs/apis/gql/gql_reference#how_to_form_literals), it has stated clearly that to form a string, the string must be wrapped by a single- or double-quote. Thus, the statement above is deemed as illegal on GAE. And in real life test, it throws an exception:
> Unknown function "string".

I suggest that the local GQL parser should be strict so as to ensure it works on the production server.

**Comment by tomwalder** [comment]
Sounds like a good upgrade! I see your PR, so will take a look at that too.

**Comment by tomwalder** [comment]
Fixed by https://github.com/tomwalder/php-gds/pull/108
