### ISSUE TITLE
Add support for Google Datastore API v1

### ISSUE THREAD

**Issue by tomwalder** [tomwalder/php-gds#109]
See here

https://cloudplatform.googleblog.com/2016/04/Google-Cloud-Datastore-gets-faster-cross-platform-API.html

**Comment by emilorol** [comment]
Hi Tom,

> Now that v1beta3 is available, we’re deprecating the old v1beta2 API with a six-month grace period before decommissioning it on September 30th, 2016.

Does that mean that the current version of GDS will stop working?

Can I help in any way?

**Comment by tomwalder** [comment]
So, the simple answer is "yes, the current version will stop working"

The more complex answer is

"support for v1beta3 is coming!"

On 15 May 2016 at 05:15, Emil Orol <notifications@github.com> wrote:

> Hi Tom,
>
> Now that v1beta3 is available, we’re deprecating the old v1beta2 API with
> a six-month grace period before decommissioning it on September 30th, 2016.
>
> Does that mean that the current version of GDS will stop working?
>
> Can I help in any way?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/109#issuecomment-219265368>
>



-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by phpso10** [comment]
how do I validate if I am using the V1beta3 API? (if I am using the Beta2, what I should do to Switch? any steps?)

**Comment by tomwalder** [comment]
The library does not yet support v1beta3, so you won't be using it ;-)

**Comment by netcell** [comment]
Does this mean my app would die on September 30th? Is there anything I can contribute to help prevent this?

**Comment by phpso10** [comment]
Tom -- can you please clarify what that means? "support for v1beta3 is coming!" and you said current version will stop working.

When exactly the build is coming out and what exact changes we need to do.
(Reason is I am using your library in Production and want to make sure I get this right)

**Comment by phpso10** [comment]
I mean -- anyway the current version can continue to work? this will disrupt.

**Comment by phpso10** [comment]
so does this means if Tom Walder doesn't provide support, all production implemented Apps will fail on September end?

**Comment by phpso10** [comment]
is anyone in the same boat?

**Comment by netcell** [comment]
It is not apocalypse. It is possible to rewrite your application with google/apiclient. I've already wrapped Tom's library before use so I think it's not rocket science. But it is sad if everone have to reimplement this for each of their apps.

I hope it is also possible to fix php-gds too. I belive if we know what is the difference between api v2 and v3 the fix would be faster?

**Comment by tomwalder** [comment]
When running this library on AppEngine, you should be using the `ProtoBuf` gateway - which uses an API called `datastore_v4`.

This is not the same as the new `v1beta3` API, nor is it the same as the `v1beta2` API - it is different. It also does not have a deprecation timeline that I am aware of.

I'll try and find out some more concrete answers.

I'll also try to expedite the `v1beta3` support - but I have to find time to do that!

**Comment by netcell** [comment]
I’m not sure I  understand correctly. 
1. I thought `ProtoBuf` uses `gRPC` which is part of the api [google/google-api-php-client](https://github.com/google/google-api-php-client)?
2. If not and `ProtoBuf` is not being deprecated, why would it be deprecated by the time `v1beta2` is deprecated? (Which would make this library fail to work?)
3. Also where do I have to look to understand `ProtoBuf` and `datastore_v4`, I found nothing on [google/google-api-php-client](https://github.com/google/google-api-php-client) and [google-api-php-client-services](https://github.com/google/google-api-php-client-services)?

I do understand that you are very busy, that's why I am looking into solving the problem by myself too :) although I don't have much experience with `php` :(

Thank you. This has been a really good library. 👍

**Comment by tomwalder** [comment]
Protocol Buffers are a generic data encoding mechanism - designed for high performance RPC.  gRPC does leverage Protocol Buffers, but they are not 1:1

1. `ProtoBuf` via `datastore_v4` on App Engine does not use gRPC
2. This library supports `datastore_v4` on App Engine AND it also supports the `v1beta2` HTTP/JSON API via the google-api-php-client (prior to version 3)
3. They are not widely published - I had to do all the learning, looking at code etc.

**Comment by phpso10** [comment]
First Thanks for your library, it's a huge task you have undertaken. We respect that. Can you please confirm if the below code will continue to work POST Sept 30th? OR  I need to wait the changes from your side.

$obj_client = GDS\Gateway\GoogleAPIClient::createGoogleClient(GDS_APP_NAME, 'gds-datastore@xxx.iam.gserviceaccount.com', GDS_KEY_FILE_PATH); 
$obj_gateway = new GDS\Gateway\GoogleAPIClient($obj_client, GDS_DATASET_ID);

try {
    
$obj_schema_channels = new GDS\Schema('xxoppo');
$obj_gateway_ns = new GDS\Gateway\ProtoBuf(null, 'xxdatastore');
$obj_store_ns = new \GDS\Store($obj_schema_channels, $obj_gateway_ns);
   $arr_channels = $obj_store_ns->fetchAll("SELECT * FROM channels where title='" . $str_bktitle . "'" );

so where exactly this will fail post sep 30th?

**Comment by tomwalder** [comment]
Did you mean to post an example with BOTH types of gateway? `GoogleAPIClient ` and `ProtoBuf`?

**Comment by netcell** [comment]
@tomwalder So when `v1beta2` is deprecated, ProtoBuff gateway would still be working but JSON API gateway would not, am I understanding this correctly? If so that would be awesome :)

Thank you again.

**Comment by phpso10** [comment]
Tom,
I just need to know which one will continue to work after Sep 30th.. or which one I should be using.
Thank you

**Comment by tomwalder** [comment]
After 30th September:

1. `ProtoBuf` gateway will continue to work, on AppEngine, as it does today. Support for the underlying `datastore_v4` API will continue.

2. The *existing* JSON API gateway, `GoogleAPIClient` will stop working, as it uses the `v1eta2` Datastore API

3. I *am* intending to add `v1beta3` support soon. I've already started work on it [here](https://github.com/tomwalder/gcloud-php/tree/datastore-v1beta3-rest) and [here](https://github.com/tomwalder/php-gds/tree/datastore-v1beta3)

**Comment by phpso10** [comment]
Okay Tom,
so I understand correctly, Users using the below code will continue to work after Sep30th without any code changes required.
$obj_schema = new GDS\Schema('channels');
$obj_gateway = new GDS\Gateway\ProtoBuf(null, 'ccdatastore');
$obj_store_ns = new \GDS\Store($obj_schema, $obj_gateway);
$arr_subs = $obj_store_ns->fetchAll("SELECT * FROM channels where createdby='XXuser'" );

Am I safe? :)
Once you say safe, I will have my cup of tea first. (I was little tensed since Android dev has started)
Thanks for your great work Tom!
-Venkat

**Comment by emilorol** [comment]
Based on what Tom said, yes, you are safe.

> ProtoBuf gateway will continue to work, on AppEngine, as it does today. Support for the underlying datastore_v4 API will continue.

**Comment by phpso10** [comment]
Phew ~ -- Thank you everyone for your support and patience.
really appreciate your help as this means a lot to me.
-V

**Comment by tomwalder** [comment]
Yep, you should be fine with that!

**Comment by phpso10** [comment]
Awesome -- you guys just made my day. Thank you everyone.

**Comment by agsola** [comment]
I've just received a mail indicating that I should stop using beta2 within one month.
I've also seen that v1 final has been released.

Is there any progress in here?

Thanks for the great work, tomwalder.

**Comment by xvautier** [comment]
Same here. Great job Tom.

**Comment by tomwalder** [comment]
Yes, progress!

The development for the v1 GA API is underway. I'll try and add a milestone soon.

It's worth noting, that **if you are running on AppEngine, using the Protocol Buffer gateway, then no changes are needed** and support will continue.

**Comment by tomwalder** [comment]
See latest dev branch here:

https://github.com/tomwalder/php-gds/tree/datastore-api-v1

**Comment by agsola** [comment]
How stable is that dev branch?

Thank you for the work!

**Comment by tomwalder** [comment]
I am using it for some production systems.

But I have not finished the test suite.
