### ISSUE TITLE
Named parameter binding doesn't seem to work for strings

### ISSUE THREAD

**Issue by nigeljohnson73** [tomwalder/php-gds#114]
If I use the following, everything works:

```php
	$key = "test";
	$gql = "SELECT * FROM " . $this->kind . " WHERE key = '" . $key . "'";
	$loaded = $this->store->fetchAll ( $gql );
```

Trying to parameterise this, I opted for:

```php
	$key = "test";
	$gql = "SELECT * FROM " . $this->kind . " WHERE key = @myKey";
	$loaded = $this->store->fetchAll ( $gql, array('myKey' => $key) );
```

This throws an exception:

`
Fatal error:  Uncaught exception 'GDS\Exception\GQL' with message 'Invalid string representation in: [key = @myKey]' in /www/gae-dmservice/api/include/GDS/Mapper/ProtoBufGQLParser.php:362
Stack trace:
#0 [internal function]: GDS\Mapper\ProtoBufGQLParser->recordWhere(Array)
#1 /www/gae-dmservice/api/include/GDS/Mapper/ProtoBufGQLParser.php(214): preg_replace_callback('/WHERE\\s+(?<whe...', Array, ' WHERE key = @m...', 1)
#2 /www/gae-dmservice/api/include/GDS/Gateway/ProtoBuf.php(330): GDS\Mapper\ProtoBufGQLParser->parse('SELECT * FROM R...', Array)
#3 /www/gae-dmservice/api/include/GDS/Gateway/ProtoBuf.php(220): GDS\Gateway\ProtoBuf->executeGqlAsBasicQuery(Object(google\appengine\datastore\v4\RunQueryRequest))
#4 /www/gae-dmservice/api/include/GDS/Gateway/ProtoBuf.php(298): GDS\Gateway\ProtoBuf->execute('RunQuery', Object(google\appengine\datastore\v4\RunQueryRequest), Object(google\appengine\datastore\v4\RunQueryResponse))
#5 /www/gae-dmservice/api/include/GDS/Store.php(232): GDS\Gateway\ProtoBuf->gql('SELECT * FROM R...', in /www/gae-dmservice/api/include/GDS/Mapper/ProtoBufGQLParser.php on line 362
`

I originally thought it was a quotes thing, so I added those into the gql:

```php
	$key = "test";
	$gql = "SELECT * FROM " . $this->kind . " WHERE key = '@myKey'";
	$loaded = $this->store->fetchAll ( $gql, array('myKey' => $key) );
```

No exception, but no values returned either. 

I eventually tracked this down to the block testing the schema in line 353 of `Mapper/ProtoBufGQLParser.php` and specifically the test at line 360 that seems to be looking for rhs (@myKey) to match `"__token__"`

If I change this to '`== self::TOKEN_PREFIX`' strings seem to work again, but I don't really understand what I've done. or if I've broken other types.

**Comment by tomwalder** [comment]
Hi.

Keys are special - they are not like other strong parameters and cannot be
bound as strings.

Although you should be able to do what you need with fetchById or
fetchByName ?

Tom

On Sunday, 15 May 2016, nigeljohnson73 <notifications@github.com> wrote:

> If I use the following, everything works:
>
>     $key = "test";    $gql = "SELECT * FROM " . $this->kind . " WHERE key = '" . $key . "'";    $loaded = $this->store->fetchAll ( $gql, array('myKey' => $key) );
>
> Trying to parameterise this, I opted for:
>
>     $key = "test";    $gql = "SELECT * FROM " . $this->kind . " WHERE key = @myKey";    $loaded = $this->store->fetchAll ( $gql, array('myKey' => $key) );
>
> This throws an exception:
>
>
> Fatal error: Uncaught exception 'GDS\Exception\GQL' with message 'Invalid
> string representation in: [key = @myKey]' in
> /www/gae-dmservice/api/include/GDS/Mapper/ProtoBufGQLParser.php:362
> Stack trace:
> #0 [internal function]: GDS\Mapper\ProtoBufGQLParser->recordWhere(Array)
> #1 /www/gae-dmservice/api/include/GDS/Mapper/ProtoBufGQLParser.php(214):
> preg_replace_callback('/WHERE\\s+(?<whe...', Array, ' WHERE key = @m...', 1)
> #2 /www/gae-dmservice/api/include/GDS/Gateway/ProtoBuf.php(330):
> GDS\Mapper\ProtoBufGQLParser->parse('SELECT * FROM R...', Array)
> #3 /www/gae-dmservice/api/include/GDS/Gateway/ProtoBuf.php(220):
> GDS\Gateway\ProtoBuf->executeGqlAsBasicQuery(Object(google\appengine\datastore\v4\RunQueryRequest))
> #4 /www/gae-dmservice/api/include/GDS/Gateway/ProtoBuf.php(298):
> GDS\Gateway\ProtoBuf->execute('RunQuery',
> Object(google\appengine\datastore\v4\RunQueryRequest),
> Object(google\appengine\datastore\v4\RunQueryResponse))
> #5 /www/gae-dmservice/api/include/GDS/Store.php(232):
> GDS\Gateway\ProtoBuf->gql('SELECT * FROM R...', in
> /www/gae-dmservice/api/include/GDS/Mapper/ProtoBufGQLParser.php on line 362
>
> I originally thought it was a quotes thing, so I added those into the gql:
>
>     $key = "test";    $gql = "SELECT * FROM " . $this->kind . " WHERE key = '@myKey'";    $loaded = $this->store->fetchAll ( $gql, array('myKey' => $key) );
>
> No exception, but no values returned either.
>
> I eventually tracked this down to the block testing the schema in line 353
> of Mapper/ProtoBufGQLParser.php and specifically the test at line 360
> that seems to be looking for rhs (@myKey <https://github.com/myKey>) to
> match "__token__"
>
> If I change this to '== self::TOKEN_PREFIX' strings seem to work again,
> but I don't really understand what I've done. or if I've broken other types.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/114>
>


-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by tomwalder** [comment]
Any luck?
