### ISSUE TITLE
 Google Protocol Buffer

### ISSUE THREAD

**Issue by AidasK** [tomwalder/php-gds#115]
Is it possible to use it in Compute Engine?

**Comment by tomwalder** [comment]
Currently, you can only use the Protocol Buffers on AppEngine.

HOWEVER, with the advent of the v1beta3 API recently, there will be gRPC support coming for Compute Engine, which will be better than Protocol Buffers.

**Comment by tomwalder** [comment]
You can use the REST API on Compute Engine.
