### ISSUE TITLE
Please add support for datatype: Text/Blob

### ISSUE THREAD

**Issue by nigeljohnson73** [tomwalder/php-gds#117]
Strings have a 500 character limit, that's bad for storing web page type documents :( Please can this be added to the roadmap, they shouldn't be too much work, should they?

In the interim, how can I store text that is over 500 characters long?

**Comment by tomwalder** [comment]
A non-indexed string should allow for up to 1MB of data, I think.

You must define it as NOT indexed though. Let me know how that goes.

**Comment by nigeljohnson73** [comment]
Ah ha!!!!! non-indexed strings can go large :) I tested it up to about 5Kb so I'm happy with that.

Thanks Tom

**Comment by AidasK** [comment]
I had the same issue. I think this could be solved by creating a new method `addText` without index parameter. It could call `addString` internally.

**Comment by tomwalder** [comment]
But you just pass FALSE in to addString as the second parameter?



On Thursday, 26 May 2016, Aidas Klimas <notifications@github.com> wrote:

> I had the same issue. I think this could be solved by creating a new
> method addText without index parameter. It could call addString
> internally.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/117#issuecomment-221866395>
>


-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by AidasK** [comment]
It was just a suggestion to prevent such issues like this. Just create another sibling method called `addText`
