### ISSUE TITLE
Error on lookup when fetching with WHERE clause & Kind with spaces

### ISSUE THREAD

**Issue by bgold0** [tomwalder/php-gds#12]
> <b>Fatal error</b>:  Uncaught exception 'Google_Service_Exception' with message 'Error calling POST https://www.googleapis.com/datastore/v1beta2/datasets/nice-virtue-798/lookup: (400) Key path element must not be incomplete:   

I get the above error for some reason when I do this (`$something_id` has an appropriate value attached to it):

    $obj_store = new GDS\Store($obj_gateway, "Something With Spaces");
    $find_item = $obj_store->fetchOne("SELECT * FROM `Something With Spaces` WHERE something_id = '".$something_id."'");
    print_r($find_item);

This only happens with a **WHERE** clause. So for example, this works perfectly fine.

    $find_item = $obj_store->fetchOne("SELECT * FROM `Something With Spaces`");

**EDIT:** I tried this same query on a *Kind* like this, and it worked.

    $find_item = $obj_store->fetchOne("SELECT * FROM `Something` WHERE something_id = '".$something_id."'");

Do you know what the problem could be?

**Comment by tomwalder** [comment]
A few questions:

1. When you say "something_id" - do you mean the object KEY Id?

2. Can you give the ID value so I can test here? (I tested with "123" and it worked OK)

3. Have you tried using parameter binding like this:

```$find_item = $obj_store->fetchOne("SELECT * FROM `Something With Spaces` WHERE something_id = @something_id", ['something_id' => $something_id]);```

**Comment by bgold0** [comment]
1. "something_id" is just a property name.  Sorry for the confusion.

2. I'm not sure what your asking. Here is my query in "full form" that doesn't work.

    $find_item = $obj_store->fetchOne("SELECT * FROM `Something With Spaces` WHERE something_id = '5183105597964288'");

3. I tried this, and still get the same error.

**Comment by bgold0** [comment]
I am sorry for the confusion, I tried using parameter binding again and it ended up working. Must have been how `$something_id` was being stored? I'm really not sure.
