### ISSUE TITLE
support for google apiclient 2.0 

### ISSUE THREAD

**Issue by naveed125** [tomwalder/php-gds#121]
Any plans to support google/apiclient:2.0? Currently we get something like:

PHP Fatal error:  Call to undefined method Google_Client::setAssertionCredentials() in .../php-gds-client/vendor/tomwalder/php-gds/src/GDS/Gateway/GoogleAPIClient.php on line 88

**Comment by tomwalder** [comment]
Yeah, there is a branch for it, which I started when that was RC2, but they kept breaking it, so I have been waiting for the official v2.0.0, which came out 3 days ago!

**Comment by tomwalder** [comment]
Also relates to #68

**Comment by tomwalder** [comment]
Closing this ticket. See #109 and 

https://github.com/tomwalder/php-gds/tree/datastore-api-v1
