### ISSUE TITLE
FetchAll returns less than 1000 but Actual count is > 1000

### ISSUE THREAD

**Issue by phpso10** [tomwalder/php-gds#130]
Not sure why this returns only 20 as count --but I have more than 900 records.

$obj_schema = new GDS\Schema('xxaas');
$obj_gateway_ns = new GDS\Gateway\ProtoBuf(null, 'bkdatastore');
$obj_store_ns = new \GDS\Store($obj_schema, $obj_gateway_ns);

$arr_subs = $obj_store_ns->fetchAll("SELECT * FROM xxaas where createdby='6229999BK9999ADMIN' );
$rowCount = count($arr_subs);
echo "FetchAll=" . $rowCount;

--what am I doing wrong ? my understand is that FetchAll should return max of 1000 records.
-- FetchAll it returns only 20 as count. ( I thought it will return a max of 1000)

**Comment by tomwalder** [comment]
The code looks reasonable. Obviously you do have a filter on your query - are you sure all the records have that same createdby value?

Have you tried running the same GQL query in the admin console to see what results you get?

If you have inserted some records with the createdby field NOT indexed then they will never show in results?

**Comment by phpso10** [comment]
Tom -- sent you an email to see if we can achieve with Cursors. please see when you get time.

**Comment by phpso10** [comment]
GQL returns fine though.

**Comment by tomwalder** [comment]
I'll reply via email!

**Comment by phpso10** [comment]
Tom graciously gave the guidance and here is the snippet. Hope this would help someone.

For the first time call, you would simply query, Fetchpage, and then use GetCursor.
and afterwards you would use as below.

$page_results= $obj_store_ns->query("SELECT * FROM logs where createdby='XXX' ORDER BY createdon desc");
$obj_store_ns->setCursor($str_bkcursor); // Tell it to start from the end of the previous page
$page_results = $obj_store_ns->fetchPage(50); // gets the first page
$str_bkcursornext = $obj_store_ns->getCursor();

The callout is, you need to have the composite index in place and its' better (at-least for me) to convert the getcursor to HexStrings and then Cache but for sure, better than offset. (particularly if you are using for Mobile Apps)

Cheers and Thanks everyone for your support.
