### ISSUE TITLE
What format are strings stored in by PHP-GDS and Datastore?

### ISSUE THREAD

**Issue by ajck** [tomwalder/php-gds#131]
Just thinking about how I can store data in the most compact way using whatever format php-gds and datastore are using? I'm thinking of doing a custom mapping in my code between 8-bit integers for example (or larger) and packing them into whatever format strings use in the library/datastore so I can translate between them on the fly and keep data as compact as possible. Also was wondering what would happen if I stored a msgpack string http://msgpack.org/ which is binary. I know I could encode to base64 but wondering if a more compact solution is possible by mapping bytes (/etc) to allowed character set range.

Thanks.

**Comment by tomwalder** [comment]
So, compact strings is not a strong point for Datastore.

Each entity is stored with all the keys, as well as value data.

What is your motivation?

**Comment by tomwalder** [comment]
Closing this off. Please update if you still want some help here!
