### ISSUE TITLE
API v1 issues with dates

### ISSUE THREAD

**Issue by tomwalder** [tomwalder/php-gds#133]
Possible differences in DATE responses from `Entity::getData()`

Need to confirm

**Comment by tomwalder** [comment]
Should be addressed in 9a16397

**Comment by agsola** [comment]
I can confirm this doesn't work properly in the main branch.

I'm getting this format:  2016-09-23 17:45:33
instead of this: 2016-09-23T17:45:33.012Z, which I was getting previously.

Is it the intended way?
Could that be personalized? I'm breaking my code being "less" accurate with time.

**Comment by tomwalder** [comment]
This is the expected behaviour in v3. The datetime formats are now the same between both the ProtoBuf and REST gateways.

https://github.com/tomwalder/php-gds#v3-over-v2

However, I can probably add a "compatibility mode" or something similar if it's a real problem for you. If so, please raise a new issue requesting that.

**Comment by agsola** [comment]
Sorry, I didn't see that.
I'll raise a new issue.
Thank you for the support.
