### ISSUE TITLE
Pagination and cursor

### ISSUE THREAD

**Issue by chapus** [tomwalder/php-gds#137]
Hi, Thanks for the library very useful for my project. I was using Datastore API beta and now im migrating my project with your code. My question is:  why fetchAll or a Query is only getting 300 results no more ?
And then I see the FetchPage with Cursors, and i can loop through the results but the function getCursor() when is the last set of results,  is still giving me a String, so im getting an infinite loop, do you know how to know when is the last set of results ?

**Comment by tomwalder** [comment]
As long as you do this (while loop) it will stop after the last page, as there will be no results in the response.

```php
$obj_book_store->query('SELECT * FROM Book');
while($arr_page = $obj_book_store->fetchPage(50)) {
    echo "Page contains ", count($arr_page), " records", PHP_EOL;
}
```

**Comment by tomwalder** [comment]
If you are not getting that behaviour, please let me know and provide a code sample.

**Comment by chapus** [comment]
Thanks, you are right. My loop check if the array of results is not empty !, and worked.
http://stackoverflow.com/questions/6934681/how-do-i-tell-if-the-returned-cursor-is-the-last-cursor-in-app-engine

I was doing a while checking the cursor, and inside doing the query and the fetchpage passing the cursor,  but the While(fetchPage) is cleaner and less code !. Thanks.
