### ISSUE TITLE
type text for long value

### ISSUE THREAD

**Issue by jodacame** [tomwalder/php-gds#147]
Please add type text for long value (Long string)

**Comment by tomwalder** [comment]
This is already supported, up to 1MB

`->addString('long_thing', false);`

It's important to turn OFF indexing, so Google does not throw an error for data longer than 1500

**Comment by jodacame** [comment]
Thank you!..

**Comment by jodacame** [comment]
Sry, again...

If i using Alternative Array Syntax https://github.com/tomwalder/php-gds#alternative-array-syntax 
How can define long string?

Good job!

**Comment by tomwalder** [comment]
So, here are a few of the examples tied together...

```php
// define a schema with a long (unindexed) string
$obj_schema = (new GDS\Schema('Book'))
   ->addString('title')
   ->addString('author', false)
   ->addString('isbn');

// The Store accepts a Schema object as its first parameter
$obj_book_store = new GDS\Store($obj_schema);

// author will be a long string
$obj_book = $obj_book_store->createEntity([
    'title' => 'The Merchant of Venice',
    'author' => 'William Shakespeare',
    'isbn' => '1840224312'
]);

```
