### ISSUE TITLE
PHP supports Google Cloud Native

### ISSUE THREAD

**Issue by phpso10** [tomwalder/php-gds#153]
Hello Everyone,
I read the article recently that now Google Cloud supports PHP (beta). Now, how do we modify the  existing GDS library connection to make use of Google Cloud Native php without modifying (rewriting) the entire code?

Thank you!

**Comment by tomwalder** [comment]
So, last time I checked the official PHP library https://github.com/GoogleCloudPlatform/google-cloud-php it only supported the REST API for Datastore.

This means that, on AppEngine Standard, which is the primary use case for PHP-GDS, PHP-GDS is significantly faster as it uses the Protocol Buffer API.

However, when NOT running on AppEngine, PHP-GDS uses the same "v3 REST API" that the official PHP library supports.

This is all AFAIK - I hope I am still up to date!

**Comment by phpso10** [comment]
I see.. Thanks Tom for educating.

**Comment by phpso10** [comment]
Closed.
