### ISSUE TITLE
App Engine PHP 7 Standard Runtime Compatibility

### ISSUE THREAD

**Issue by tomwalder** [tomwalder/php-gds#162]
Just putting this here as I work through (probably many) issues running on PHP 7.2 GAE Standard...

**Comment by iamacarpet** [comment]
@tomwalder how did you get on with the REST API on the new runtime?
Is the performance comparable to how it was on App Engine PHP 5.5?

I'm still interested if GRPC/protobuf is faster like it was on PHP 5.5.
Google's official library doesn't support it, but it does look like it's available externally and not just via the service bridge from the old App Engine runtimes.
https://cloud.google.com/datastore/docs/reference/data/rpc/

Debating if it would be worth learning GRPC to make a new ProtobufExternal Gateway, as it looks like the methods are mostly the same.

What are your thoughts?

**Comment by tomwalder** [comment]
Closing this with the release of `v5.0.0`
