### ISSUE TITLE
Error refreshing the OAuth2 token

### ISSUE THREAD

**Issue by bgold0** [tomwalder/php-gds#19]
I got this message recently during an action that only uses php-gds. This is the first time seeing it and it doesn't come up at the moment during the same action. It happened within a 30 minute interval and then I stopped seeing it. Would there be a reason this would come up using php-gdb?

    PHP Fatal error:  Uncaught exception 'Google_Auth_Exception' with message 'Error refreshing the OAuth2 token, message: '<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"/><title>Sorry...</title><style> body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style></head><body><div><table><tr><td><b><font face=times color=#0039b6 size=10>G</font><font face=times color=#c41200 size=10>o</font><font face=times color=#f3c518 size=10>o</font><font face=times color=#0039b6 size=10>g</font><font face=times color=#30a72f size=10>l</font><font face=times color=#c41200 size=10>e</font></b></td><td style="text-align: left; vertical-align: bottom; padding-bottom: 15px; width: 50%"><div style="border-bottom: 1px solid #dfdfdf;">Sorry...</div></td></tr></table></div><div style="margin-left: 4em;"><h1>We're sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.</p></div><div style="margin-lef

    in /base/data/home/apps/.../vendor/google/apiclient/src/Google/Auth/OAuth2.php on line 358

**Comment by tomwalder** [comment]
So, pretty sure this is because of the Google Cloud issues yesterday...

https://status.cloud.google.com/incident/appengine/15006

**Comment by bgold0** [comment]
Ah awesome. Thanks for the link.
