### ISSUE TITLE
Google PHP API Upgrade, things stop working

### ISSUE THREAD

**Issue by bgold0** [tomwalder/php-gds#23]
I know you are probably getting tired of hearing from me. My only hope is these posts help other people like myself. Thank you, yet again, for taking the time. I don't know where I'd be without this library. Probably wasting money on MySQL.

I just ran an update on my composer and I guess it updated my Google PHP API. I have a scrip tthat checks my session id and `fetchById()` to find it. It works with my old vendor folder but my new one, it doesn't find it. The `fetchById()` just returns `1`.

Here are some pieces from my new composer.lock for php-gds and google api.

    "source": {
        "type": "git",
        "url": "https://github.com/tomwalder/php-gds.git",
        "reference": "94e504516d359ee82c3b2b83e32896bd374919a0"
    },
    "dist": {
        "type": "zip",
        "url": "https://api.github.com/repos/tomwalder/php-gds/zipball/94e504516d359ee82c3b2b83e32896bd374919a0",
        "reference": "94e504516d359ee82c3b2b83e32896bd374919a0",
        "shasum": ""
    }

    "source": {
        "type": "git",
        "url": "https://github.com/google/google-api-php-client.git",
        "reference": "c9eb74a5e24e5eb81c552c44d33ac77c39c94a85"
    },
    "dist": {
        "type": "zip",
        "url": "https://api.github.com/repos/google/google-api-php-client/zipball/c9eb74a5e24e5eb81c552c44d33ac77c39c94a85",
        "reference": "c9eb74a5e24e5eb81c552c44d33ac77c39c94a85",
        "shasum": ""
    },

I couldn't find what my old references were. I guess my question is, are there specific "versions" that I need to abide by for php-gds. And assuming there is, where do I find out this information?

**Comment by tomwalder** [comment]
This could be a bug. I've recently updated the fetchById method.

You could use v1.2 (set it in composer) or 1.1, depending upon which features you need. The changes to fetchById are only in dev-master.

Check the "releases" list on github.

**Comment by bgold0** [comment]
Okay phewf. I went to `df23d64cfe20a15da5cebf60ad1e8c350471d26b` and it seems to be working. I was at a slightly lower version of `02725ad5c2eac1f69c9721f2402de4c821dc5b1d` before upgrading.

Just figure out how this composer.lock thing works so I'll be more careful next time.

**Comment by bgold0** [comment]
Sorry, version `1.1.0` works fine. The error was due to some **very werid** issue I am having with my Safari browser.

While running Safari, my logs spit out errors. It works in Safari private browser mode, chrome, firefox, my iPhone, but not regular safari; yet it works on other machines with the same version of Safari.
