### ISSUE TITLE
"No entity found"

### ISSUE THREAD

**Issue by bgold0** [tomwalder/php-gds#25]
Is anyone else having an issue with a lot of their datastore entities being "un-editable" in the Developers Console?

I always get this error when clicking on an entity ID:

> We could not find an entity with namespace: "{NAMESPACE}", kind: "{KIND}", and identifier "id={ID}"

[Google Issue Reported](https://code.google.com/p/googleappengine/issues/detail?id=11847&can=4&colspec=ID%20Type%20Component%20Status%20Stars%20Summary%20Language%20Priority%20Owner%20Log)

**Comment by tomwalder** [comment]
I have not personally had the issue - but I've not been working with namespaces the last couple of days.

**Comment by bgold0** [comment]
Looks like I'm [not alone with this problem](http://stackoverflow.com/questions/29496240/no-entity-found-developer-datastore-console?noredirect=1#comment47185870_29496240).

It was working with some entities and not in others so I had a jerking suspicion that it had to do with the way I was creating it through php-gds but I think I've confirmed it is not the case. Since everything works fine in the old school dev console.
