### ISSUE TITLE
Weird "stderr" error popping up in local dev console

### ISSUE THREAD

**Issue by bgold0** [tomwalder/php-gds#26]
> stderr: Unable to delete function dlUnable to delete function mb_send_mail

I have the following code that produces the above error. When I remove this code, the error disappears.
        
    $email = "something@anything.com";

	$obj_google_client = GDS\Gateway::createGoogleClient('{APP_ID}', "{EMAIL}", "service.p12");
	$obj_gateway = new GDS\Gateway($obj_google_client, '{APP_ID}', "{NAMESPACE}");

	$obj_store = new GDS\Store($obj_gateway, "Users");
	$check_email = $obj_store->fetchOne("SELECT * FROM `Users` WHERE email = @email", ['email' => $email]);

	if(!empty($check_email)) die('{"result": "EMAIL_TAKEN"}');

**Comment by bgold0** [comment]
It definitely has to do with the following line of code:

    $check_email = $obj_store->fetchOne("SELECT * FROM `Users` WHERE email = @email", ['email' => $email]);

**Comment by tomwalder** [comment]
Try without the back ticks?

On Monday, April 13, 2015, bgold0 <notifications@github.com> wrote:

> It definitely has to do with the following line of code:
>
> $check_email = $obj_store->fetchOne("SELECT * FROM `Users` WHERE email = @email", ['email' => $email]);
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/26#issuecomment-92423156>.
>


-- 
*Tom Walder*, CTO*Call*: 0845 521 0444 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>This
message is private and confidential. If you have received this message in
error, please notify us and remove it from your system. Doctor Net Limited
t/a Docnet is a company registered in England and Wales. Registered number:
3303804. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by bgold0** [comment]
Not sure what you mean by without "back ticks". I tried the following code and get a new error about a different function it can't delete.

    $check_email = $obj_store->fetchAll("SELECT * FROM `Users` WHERE email = '".$email."'");

![screen shot 2015-04-13 at 12 59 11 pm](https://cloud.githubusercontent.com/assets/4645400/7120699/ff350800-e1dc-11e4-95bf-a74c320c310a.png)

**Comment by tomwalder** [comment]
Might be worth revering back to an earlier version of the Google api
library - in case there is a bug in that.

I can test this out later.

What O/S are you using?

Is the issue only dev or production or both?


On Monday, April 13, 2015, bgold0 <notifications@github.com> wrote:

> Not sure what you mean by without "back ticks". I tried the following code
> and get a new error about a different function it can't delete.
>
> $check_email = $obj_store->fetchAll("SELECT * FROM `Users` WHERE email = '".$email."'");
>
> [image: screen shot 2015-04-13 at 12 59 11 pm]
> <https://cloud.githubusercontent.com/assets/4645400/7120699/ff350800-e1dc-11e4-95bf-a74c320c310a.png>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/26#issuecomment-92424926>.
>


-- 
*Tom Walder*, CTO*Call*: 0845 521 0444 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>This
message is private and confidential. If you have received this message in
error, please notify us and remove it from your system. Doctor Net Limited
t/a Docnet is a company registered in England and Wales. Registered number:
3303804. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by bgold0** [comment]
I'm not sure if the issue is only in dev or production. I can check if you want but I've found out the issue. It doesn't make much sense though.

I had already declared `$obj_google_client` and `$obj_gateway` in a included php file at the top of the page. When I removed the re-declaration in my above code, the error went away.

**Comment by bgold0** [comment]
Ugh...well today I jumped on my local dev site and didn't make any changes and now this starts to occur and doesn't even load my page anymore:

> <b>Fatal error</b>:  fopen(): Invalid response from API server. in <b>/{PATH}/vendor/google/apiclient/src/Google/IO/Stream.php</b> on line <b>130</b><br />
stderr:
Unable to delete function dlUnable to delete function mb_send_mail

**Comment by tomwalder** [comment]
Did you find something to resolve this?



On Tuesday, April 14, 2015, bgold0 <notifications@github.com> wrote:

> Closed #26 <https://github.com/tomwalder/php-gds/issues/26>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/26#event-281365616>.
>


-- 
*Tom Walder*, CTO*Call*: 0845 521 0444 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>This
message is private and confidential. If you have received this message in
error, please notify us and remove it from your system. Doctor Net Limited
t/a Docnet is a company registered in England and Wales. Registered number:
3303804. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by bgold0** [comment]
Yesterday I thought it was because I re-declared `$obj_google_client` and `$obj_gateway` so I closed it. Now I get it from multiple pages of my project 50% of the time I load my page.. so I'm pretty confused.

This doesn't happen in a deployed app engine, just my local.

**Comment by eizzel** [comment]
I'm also getting the "Unable to delete function dlUnable to delete function mb_send_mail" error on my local dev server though I haven't been able to trace what's causing it. I'm running a Yii2 project and this bug breaks the debugging module but the project runs fine.

**Comment by arie-piscator** [comment]
Setting php55 to php in app.yaml and restarting the dev server solved this issue for me. In production php55 works fine.

**Comment by atrauzzi** [comment]
Got to this ticket via a google search for `Unable to delete function mb_send_mail` as I'm encountering this same issue on OSX.

Interestingly, the fix to change `php55` to `php` does work.  But I'm wondering if that's an appropriate solution?  The following page has this message in a nice blue notice-box -  https://cloud.google.com/appengine/docs/php/ :

![screen shot 2015-07-08 at 3 28 04 am](https://cloud.githubusercontent.com/assets/115199/8566124/649af4e8-2521-11e5-913e-6ee679aa68b2.png)

Wondering if this is worth opening as a ticket/question with google?

**Comment by arie-piscator** [comment]
Good to mention this. Uploading to App Engine with php (an not php55) doesn't work anymore. I posted this Unable to delete function mb_send_mail error on StackOverflow where a guy from google was looking into it.

http://stackoverflow.com/questions/31112057/error-500-on-gae-local-dev-server-with-laravel-and-php-5-5

 But it could be worth opening a question directly with google too.

**Comment by atrauzzi** [comment]
I posted an answer to the StackOverflow question, which includes a link to a ticket I just made: https://code.google.com/p/googleappengine/issues/detail?id=12127&thanks=12127&ts=1436346387

Let's all make sure to say a blurb on there as I'm guessing this is happening to anyone trying to use Laravel on GAE. :)
