### ISSUE TITLE
Possible to connect php-gds to local datastore?

### ISSUE THREAD

**Issue by bgold0** [tomwalder/php-gds#27]
How do you guys develop your applications on your local machine before deploying them to the app engine? Sending/retrieving data to a deployed datastore is very slow and time consuming.

Is there a way to connect php-gds to a local datastore?

**Comment by tomwalder** [comment]
So, the roadmap includes an upgrade to allow a "local" gateway - which
would behave exactly as per the current gateway object (I.e. You continue
to use the Store object for everything but pass in the alternative Gateway
for development).

No ETA right now.



On Tuesday, April 14, 2015, bgold0 <notifications@github.com> wrote:

> How do you guys develop your applications on your local machine before
> deploying them to the app engine? Sending/retrieving data to a deployed
> datastore is very slow and time consuming.
>
> Is there a way to connect php-gds to a local datastore?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/27>.
>


-- 
*Tom Walder*, CTO*Call*: 0845 521 0444 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>This
message is private and confidential. If you have received this message in
error, please notify us and remove it from your system. Doctor Net Limited
t/a Docnet is a company registered in England and Wales. Registered number:
3303804. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by bgold0** [comment]
Very cool! Can't wait. You do amazing work.

For the time being, I happened up on this URL that may work: https://gist.github.com/pwalsh/b8563e1a1de3347a8066

**Comment by bgold0** [comment]
Mhmm actually didn't work as easily as I thought it would
