### ISSUE TITLE
composer google dependency broken

### ISSUE THREAD

**Issue by larrykluger** [tomwalder/php-gds#30]
I received this composer error:
  Problem 1
    - Installation request for tomwalder/php-gds dev-master -> satisfiable by tomwalder/php-gds[dev-master].
    - tomwalder/php-gds dev-master requires google/apiclient dev-master -> no matching package found.

Is the problem that the google code seems to be at https://github.com/google/google-api-php-client ?
Or that the recommendation from Google is to use 
"google/apiclient": "1.0.*@beta"

-- See https://developers.google.com/api-client-library/php/start/installation

Thank you

**Comment by tomwalder** [comment]
Hey there,

Thanks for raising the issue - I'll check it out ASAP!

**Comment by tomwalder** [comment]
Hi there,

So right now the releases from the Google API are quite out of date (latest, `1.1.2` is November last year).

As such, I point at the `dev-master` branch from `php-gds`.

In order for this to work, you can add the following line to your composer file

Example:
https://github.com/tomwalder/php-gds-demo/blob/master/composer.json#L10

Reference:
https://getcomposer.org/doc/04-schema.md#minimum-stability


I will also ask the Google guys when they are planning another release. I'll leave this ticket open until then.

**Comment by larrykluger** [comment]
Hi Tom,

Thank you for your time on this. I'm a composer newbie, so the extra info
on how to setup my composer file is much appreciated.

I've just tried your advice and it works great.

Regards,
Larry

**Comment by tomwalder** [comment]
You can see updates on this thread here

https://github.com/google/google-api-php-client/issues/547

**Comment by tomwalder** [comment]
Upstream have tagged 1.1.3, so I will update here soon...

**Comment by tomwalder** [comment]
1.2.0 released
