### ISSUE TITLE
Update documentation for 2.x series

### ISSUE THREAD

**Issue by tomwalder** [tomwalder/php-gds#35]

**Comment by tomwalder** [comment]
This will probably be the last job! But it has been started.

**Comment by bgold0** [comment]
Woo! Keep up the good work Tom. When this goes beta, i'd be happy to test it with some heavy usage!

**Comment by tomwalder** [comment]
Sounds brill.

I'm pretty close to Beta I think. Will keep you posted!

On Thursday, June 18, 2015, bgold0 <notifications@github.com> wrote:

> Woo! Keep up the good work Tom. When this goes beta, i'd be happy to test
> it with some heavy usage!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/35#issuecomment-113251203>.
>


-- 
*Tom Walder*, CTO*Call*: 0845 521 0444 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>This
message is private and confidential. If you have received this message in
error, please notify us and remove it from your system. Doctor Net Limited
t/a Docnet is a company registered in England and Wales. Registered number:
3303804. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by tomwalder** [comment]
Hey there.

2.0 has gone BETA tonight.

dev-master is now the 2.0 branch.

Testing appreciated. Keep your eye on the BC break constructor for GDS\
Store.

Tom



On Thursday, June 18, 2015, bgold0 <notifications@github.com> wrote:

> Woo! Keep up the good work Tom. When this goes beta, i'd be happy to test
> it with some heavy usage!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/35#issuecomment-113251203>.
>


-- 
*Tom Walder*, CTO*Call*: 0845 521 0444 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>This
message is private and confidential. If you have received this message in
error, please notify us and remove it from your system. Doctor Net Limited
t/a Docnet is a company registered in England and Wales. Registered number:
3303804. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by bgold0** [comment]
Hey Tom, just got back from some vacation and looking to try this BETA out. Really cool that the Gateway is optional now.

But now that the Gateway is optional, I can't determine how to set up the project id. How are they connected now? Sorry if that's a silly question.

**Comment by tomwalder** [comment]
So a MAJOR feature of 2.0 is that it can talk to your local Datastore.

By default, it will automatically talk to your local Datastore in development and your Live Datastore when deployed to App Engine.

BUT, there are a couple of things to note.

1. The local Datastore environment does NOT support GQL queries

2. You can still talk to a live Datastore instance from your local dev environment - you just have to specify the Gateway.

**Comment by tomwalder** [comment]
You might consider something like this:

```php
define('IS_APP_ENGINE', (isset($_SERVER['SERVER_SOFTWARE']) && strpos($_SERVER['SERVER_SOFTWARE'], 'Google App Engine') !== FALSE));
if(IS_APP_ENGINE) {
   $obj_gateway = new \GDS\Gateway\ProtoBuf('dataset-here');
} else {
   $obj_client = \GDS\Gateway\GoogleAPIClient::createClientFromJson('service-account.json');
   $obj_gateway = new \GDS\Gateway\GoogleAPIClient($obj_client, 'dataset-here');
}
```

Then pass that gateway into the Store. 

The above code (if not obvious) will use the API client when running locally and the ProtoBuf when running in App Engine

**Comment by bgold0** [comment]
Thanks tom, just trying to wrap my head around this. Will the above code make it so it always grabs from the live database?

I change my namespaces a lot throughout my code, so do you think the appropriate workaround would be to declare all of my namespaces in that check like this:

	define('IS_APP_ENGINE', (isset($_SERVER['SERVER_SOFTWARE']) && strpos($_SERVER['SERVER_SOFTWARE'], 'Google App Engine') !== FALSE));
	if(IS_APP_ENGINE) {
	   $obj_gateway1 = new \GDS\Gateway\ProtoBuf('app-engine-id', 'namespace1');
	   $obj_gateway2 = new \GDS\Gateway\ProtoBuf('app-engine-id', 'namespace2');
	   $obj_gateway3 = new \GDS\Gateway\ProtoBuf('app-engine-id', 'namespace3');
	   $obj_gateway4 = new \GDS\Gateway\ProtoBuf('app-engine-id', 'namespace4');
	   $obj_gateway5 = new \GDS\Gateway\ProtoBuf('app-engine-id', 'namespace5');
	} else {
	   $obj_client = \GDS\Gateway\GoogleAPIClient::createClientFromJson('service-account.json');
	   $obj_gateway1 = new \GDS\Gateway\GoogleAPIClient($obj_client, 'app-engine-id', 'namespace1');
	   $obj_gateway2 = new \GDS\Gateway\GoogleAPIClient($obj_client, 'app-engine-id', 'namespace2');
	   $obj_gateway3 = new \GDS\Gateway\GoogleAPIClient($obj_client, 'app-engine-id', 'namespace3');
	   $obj_gateway4 = new \GDS\Gateway\GoogleAPIClient($obj_client, 'app-engine-id', 'namespace4');
	   $obj_gateway5 = new \GDS\Gateway\GoogleAPIClient($obj_client, 'app-engine-id', 'namespace5');
	}

**Comment by tomwalder** [comment]
> Will the above code make it so it always grabs from the live database?

YES, it will always speak to a live Datstore with my example

> do you think the appropriate workaround would be to declare all of my gateways in that check like this:

YES, that's fine. You might want to consider a Factory/Singleton or better still a Di container, but that might be a lot of work.

*IMPOTANT* I am 95% complete with a local GQL parser - so watch this space in the next 24 hours!

**Comment by bgold0** [comment]
Awesome, thanks @tomwalder. I'll hold out until the next update before I start doing some heavy changes. Thanks again for all your hard work. Honestly don't think I'd be using Datastore if it wasn't for your library.

**Comment by tomwalder** [comment]
Closing this ticket as the documentation is now 99% updated to reflect 2.0
