### ISSUE TITLE
Bug "Error calling POST...503 back end error" in  namespace_create.php

### ISSUE THREAD

**Issue by larrykluger** [tomwalder/php-gds#40]
I received this error when running the namespace_create.php example:

Fatal error: Uncaught exception 'Google_Service_Exception' with message 'Error calling POST https://www.googleapis.com/datastore/v1beta2/datasets/DS1/commit: (503) Backend Error' in .../vendor/google/apiclient/src/Google/Http/REST.php:110
Stack trace:
#0 .../vendor/google/apiclient/src/Google/Http/REST.php(62): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request), Object(Google_Client))
#1 [internal function]: Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))
#2 .../vendor/google/apiclient/src/Google/Task/Runner.php(174): call_user_func_array(Array, Array)
#3 .../vendor/google/apiclient/src/Google/Http/REST.php(46): Google_Task_Runner->run()
#4 .../vendor/google/apiclient/src/Google/Client.php(590): Google in .../vendor/google/apiclient/src/Google/Http/REST.php on line 110

Could it be that I don't understand what credentials are needed?
I downloaded the .p12 file and am using the Console's "Service Account / Email address" as the php-gds library's "GDS_SERVICE_ACCOUNT_NAME" 

For the GDS_APP_NAME and GDS_DATASET_ID I'm just using text strings--I did not get their value from the Consoler...

Thank you for any pointers,
Larry

**Comment by larrykluger** [comment]
More investigation: the Google API Console shows that the requests came in ok.

**Comment by tomwalder** [comment]
I've not personally had the 503 error before.

503, in HTTP terms, usually means a transient error.

Are you still seeing the problem?

**Comment by larrykluger** [comment]
Just tried it now, same 503 problem. I'm just using app-related text strings for  GDS_APP_NAME and GDS_DATASET_ID -- is that ok?

**Comment by tomwalder** [comment]
So, it depends. Usually, those 2 values need to be EXACTLY the same as your "application id" from the developer console.

So, if you access your app as "http://myapphere.appspot.com" then the string you need is "myapphere"

**Comment by larrykluger** [comment]
Solved! That was the problem. I am not running the app itself on Google so there is no appspot domain name. Here is what I suggest adding to the ReadMe or to the sample config file:

~ ~ ~ ~ ~ ~ ~ 
Set both GDS_APP_NAME and GDS_DATASET_ID to your Google Developer "Project ID."

Your Project ID is available from the "Overview" screen in the Developer Console. https://console.developers.google.com
~ ~ ~ ~ ~ ~ ~ 

Thanks again for the great software and for your time!

Regards,
Larry

**Comment by tomwalder** [comment]
No problem, best of luck!
