### ISSUE TITLE
Select records with Boolean property

### ISSUE THREAD

**Issue by mivale** [tomwalder/php-gds#50]
It should be possible to define a schema with a boolean property

`(new \GDS\Schema('Book'))->addBoolean('lent');`

and then retrieve any records that have the `lent` flag set to true

```
$this->fetchOne("SELECT * FROM Book WHERE lent = @lent", [
	'lent' => true
]);
```

currently this query is not returning any records

This might be of interest in issue https://github.com/tomwalder/php-gds/issues/48

**Comment by tomwalder** [comment]
Sounds like a bug. I'll look into it!

Is that local dev server or live? Or both?

Tom

On Sunday, July 12, 2015, Michiel van Leening <notifications@github.com>
wrote:

> It should be possible to define a schema with a boolean property
>
> (new \GDS\Schema('Book'))->addBoolean('lent');
>
> and then retrieve any records that have the lent flag set to true
>
> $this->fetchOne("SELECT * FROM Book WHERE lent = @lent", [
>     'lent' => true
> ]);
>
> currently this query is not returning any records
>
> This might be of interest in issue #48
> <https://github.com/tomwalder/php-gds/issues/48>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/50>.
>


-- 
*Tom Walder*, CTO*Call*: 0845 521 0444 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>This
message is private and confidential. If you have received this message in
error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by mivale** [comment]
It's local dev server - i haven't tested it live
