### ISSUE TITLE
There is a default 20 limit?

### ISSUE THREAD

**Issue by gdarruda** [tomwalder/php-gds#57]
I'm using the fetchAll command but only 20 rows is returned every time. I put a LIMIT on my query and it works overriding the "default" 20 rows limits. This way I get only 20 lines:
```
$store = new Store($schema);
$table = $schema->getKind();

$gql = "SELECT * FROM {$table} WHERE dateTime >= @beginDate AND dateTime <= @endDate AND metricType = @metric";

return $store->fetchAll($gql, $filters);
```
This way my LIMIT clause overrides the default LIMIT

```
$store = new Store($schema);
$table = $schema->getKind();

$gql = "SELECT * FROM {$table} WHERE dateTime >= @beginDate AND dateTime <= @endDate AND metricType = @metric LIMIT 100";

return $store->fetchAll($gql, $filters);
```

**Comment by tomwalder** [comment]
Hey there,

I'll take a look!

**Comment by tomwalder** [comment]
so, nothing in my code should limit to 20 by default.

BUT, there is some talk here about a default batch size of 20
https://cloud.google.com/appengine/docs/python/datastore/queryclass?hl=en

Can you confirm a couple of things for me:

1. Is this running locally or on live App Engine?

2. Are you using the Protocol Buffer Gateway or the JSON API? Your code sample suggests you are using the default Protocol Buffer.

Thanks!

**Comment by gdarruda** [comment]
1. It occurs on both: local and live App engine.
2.  I'm using Protocol Buffer Gateway. With JSON API this problem does not occur.

**Comment by tomwalder** [comment]
I've replicated locally - I'll update here once i've made some more progress

**Comment by tomwalder** [comment]
So this is down to a default batching mechanisms in the Protocol Buffer layer. There are a couple of quick fixes. I'll most likely add an increased batch size of 1,000 - which is hinted at on other Google docs. I'll update again later.

**Comment by gdarruda** [comment]
Thanks for the attention!

**Comment by tomwalder** [comment]
This is now resolved in `dev-master`
