### ISSUE TITLE
Support insert of Entities, not just arrays

### ISSUE THREAD

**Issue by atrauzzi** [tomwalder/php-gds#58]
Right now to insert new records, you have to pass an array, which in turn will return an instance of `Entity`.

The method `upsert` however supports taking an array of entities.

If I instantiate an entity myself, it would be nice to be able to just call a method to insert it, without performing an upsert (fail on duplicate?) and without having to supply an array.

**Comment by tomwalder** [comment]
It sounds like you are talking about the "alternative array syntax" for creating `Entity` objects.

You can also just create an `Entity` and insert it, like this:

```php
// Create a simple Entity object
$obj_book = new GDS\Entity();
$obj_book->title = 'Romeo and Juliet';
$obj_book->author = 'William Shakespeare';
$obj_book->isbn = '1840224339';

// Insert into the Datastore
$obj_store->upsert($obj_book);
```

Does that help?

**Comment by atrauzzi** [comment]
I think so.  So is `upsert` the only choice for creating new entities?  I guess what I'm referring to is "what if I want duplicate entities to trigger an exception?"

But that might not be an option here?

**Comment by tomwalder** [comment]
This library does not look for duplicate Entities.

The concept behind Datastore is a "put" model, where you can replace an entire entity with another one - where the "Key" matches.

If you give me a scenario, I might be able to help.

You may want to do a "fetch and insert" in a transaction - if you are trying to do something like create unique token records or something.

**Comment by atrauzzi** [comment]
I think all I need in this situation is to not overwrite data if a specific value already exists.  Whether it's in the key or a property in the data.

So if I had this in my datastore:

    {
        id: 1
        sequence: 56
    }

And I try to write a new document:

    {
        sequence: 56
    }

I need the datastore to reject that data.

**Comment by tomwalder** [comment]
It *feels* like you are trying to mimic the "unique index constraint" offered by MySQL and similar relational databases. This does not exist in Datastore.

So, you will have to do a "fetch then put" cycle. 

Something roughly like this...

`->beginTransaction()`
`->fetchOne('SELECT * FROM Thing WHERE sequence = @seq', ['seq' => 56]);`
.. then if there is no result ..
`->upsert(some new entity)`

I also recommend doing that in a transaction.

**Comment by atrauzzi** [comment]
If I do it in a transaction, will that ensure that during my fetch+check, no other client comes in and insert the "next" ID?

**Comment by tomwalder** [comment]
I would _really_ like to understand what you are trying to achieve before I suggest a specific path.

There are ways to achieve most things in Datastore - including incremental values, unique IDs. etc. etc. - but I kind of need to know what your goal/business-problem is before I can make a good recommendation?

Cheers

**Comment by atrauzzi** [comment]
I'm looking at implementing event sourcing on top of GDS.  So in order to do that, I have to ensure that each record has a sequence number that does not already exist.  That way I can handle optimistic concurrency etc...

So the issue is, in the time that I fetch an entity, another client could have come and written a value with one that the original client will at that point mistakenly assume hasn't been used yet.

I need a mechanism in the system such that I can have clients attempt retries until they finally write a sequence value to the system that isn't already claimed.

**Comment by tomwalder** [comment]
OK, so if you want to generate unique sequential integers, I suggest using a "counter" object - which you transactionally increment. This means only one thread gets to increment from 50 to 51, even if several are trying.

Fortunately, there is an example of this in my code!

https://github.com/tomwalder/php-gds/blob/master/examples/transaction_update.php

**Comment by tomwalder** [comment]
Has this helped? if so, I'll close the issue. Cheers.

**Comment by tomwalder** [comment]
I'll close this down. Please feel free to re-open if needed.

**Comment by atrauzzi** [comment]
Sounds good, I'll give your suggestion a shot next chance I get! :)
