### ISSUE TITLE
Integer's resetting on upsert?

### ISSUE THREAD

**Issue by bgold0** [tomwalder/php-gds#59]
I have the following script that get's run. For some reason, after this run's, the `credits` gets turned to `0` no matter what the number is at.

Do you know why this would be happening? Am I doing something wrong?

I am using version 1.2 since i haven't had a chance to change my syntax for 2.0 yet.

	$obj_user_schema = (new GDS\Schema('Users'))->addString('name', TRUE)->addInteger('credits', TRUE);

	$obj_user_store = new GDS\Store($obj_global_gateway, $obj_user_schema);
	$find_user = $obj_user_store->fetchById("123456789");

	if(!empty($find_user))
	{
		$find_user->name = "changing my name";
		$obj_user_store->upsert($find_user);
	}

**Comment by tomwalder** [comment]
There is a chance it's related to a 32/64 bit integer issue.

What sorts of values are in the "credits" field?




On Thursday, August 20, 2015, bgold0 <notifications@github.com> wrote:

> I have the following script that get's run. For some reason, after this
> run's, the credits gets turned to 0 no matter what the number is at.
>
> Do you know why this would be happening? Am I doing something wrong?
>
> I am using version 1.2 since i haven't had a chance to change my syntax
> for 2.0 yet.
>
> $obj_user_schema = (new GDS\Schema('Users'))->addString('name', TRUE)->addInteger('credits', TRUE);
>
> $obj_user_store = new GDS\Store($obj_global_gateway, $obj_user_schema);
> $find_user = $obj_user_store->fetchById("123456789");
>
> if(!empty($find_user))
> {
>     $find_user->name = "changing my name";
>     $obj_user_store->upsert($find_user);
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/59>.
>


-- 
*Tom Walder*, CTO*Call*: 0845 521 0444 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>This
message is private and confidential. If you have received this message in
error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by bgold0** [comment]
It's just max 3 digit number, so I don't think that's the issue. I think I may have had a schema declared somewhere on a callback where index may have been set to FALSE. That may have been the reason because it doesn't seem to be happening anymore.

I'll re-open if I see it happen again. Thanks for the fast reply as always. Looking forward to finally checking out 2.0;
