### ISSUE TITLE
Entities added to datastore are not immediately available

### ISSUE THREAD

**Issue by xcodewarrier** [tomwalder/php-gds#60]
$userObj = new \GDS\Entity();
    $userObj->username = $username;
    $this->users_store->upsert($userObj);  
    
    $q = "SELECT * from users";
    $this->users_store->query($q);
    $result = $this->users_store->fetchAll($q);
    
    var_dump($result);

$result contains all previous entities except for the one just added.

**Comment by tomwalder** [comment]
Hey there.

You may be seeing the effect of "Eventual Consistency"

https://cloud.google.com/datastore/docs/articles/balancing-strong-and-eventual-consistency-with-google-cloud-datastore/#h.tf76fya5nqk8

If you run the same query shortly afterwards, are the Entities there?

If you use a similar set of code to your example, by try `getById()` passing in the ID of the newly generated Entity, does that return OK?

**Comment by tomwalder** [comment]
Closing this off for now. Please re-open if needed.
