### ISSUE TITLE
Cannot Fetch Child Record by Name Using Protocol Buffers

### ISSUE THREAD

**Issue by GeekLad** [tomwalder/php-gds#62]
It seems as though ```GDS\Store::fetchByName()``` breaks when you attempt to fetch a child entity by name.  I'm attempting this with an App Engine web application in the development environment, storing the entities in a local development datastore.  I haven't checked to see if the bug persists if you attempt to do this when making API calls to a "production" Google Datastore.  I'm using Protocol Buffers, not the API client.

Here's some simple code to reproduce:

```php
// Set up a simple parent entity
$parent_schema = (new GDS\Schema('Parent'))->addString('something');
$parent_store = new GDS\Store($parent_schema);
$parent_entity = $parent_store->createEntity([
	'something' => 'foo'
])->setKeyName('Dad');
$parent_store->upsert($parent_entity);

// Set up a simple child entity
$child_schema = (new GDS\Schema('Child'))->addString('something_else');
$child_store = new GDS\Store($child_schema);
$child_entity = $child_store->createEntity([
	'something_else' => 'bar'
]);
$child_entity->setKeyName('Son');
$child_entity->setAncestry($parent_entity);  // Here's where we set the ancestry
$child_store->upsert($child_entity);  

// At this point, both entities are properly stored in the datastore, 
// with the proper relation set between the child to the parent

$fetched_child = $child_store->fetchByName('Son'); // $fetched_child comes back NULL :-(
```

**Comment by tomwalder** [comment]
Hey there.

This is expected behaviour currently.

`fetchByName()` and `fetchById()` only currently support "root" entities.

I talk a little bit about this is the documentation here:
https://github.com/tomwalder/php-gds#queries-gql--the-default-query

You might want to consider using `fetchEntityGroup ()`

Hope this helps.

Tom

**Comment by GeekLad** [comment]
Thanks for the clarification Tom, and sorry about the confusion.  I'll close this out.

**Comment by GeekLad** [comment]
I'm not sure how to query by name/ID using fetchEntityGroup.  I tried creating a new entity and setting the name, but that's not working:

```php
$query_child = new GDS\Entity();
$query_child->setKeyName('Son');
$fetched_child = $child_store->fetchEntityGroup($query_child);
```
How would I query for the child by name using the fetchEntityGroup method?

**Comment by bresmith** [comment]
I would also like to know how to retrieve children using the fetchEntityGroup method.  Any updates on this?

**Comment by iragx** [comment]
I would like to know if I send data from the android to a project using the this library is it still like in MySql? 192.168.1.1/projectFolder/phpFile ... still the same process? I wanted to send a data from my android app to GAE in local storing the data into the datastore using this library.
