### ISSUE TITLE
Was on v1.2.0 and everything is now broken

### ISSUE THREAD

**Issue by bgold0** [tomwalder/php-gds#63]
Hi Tom,

I'm having big problems with my application right now. I haven't had the time to switch to 2.0 so I've been using 1.2.0. I'm assuming is has to do with 1.1.3 not being valid anymore for `google/apiclient`?

When you have a moment, could you explain what I need to do? I've tried using composer to download v1.2.1 like so:

    "google/apiclient": "1.1.4",
    "tomwalder/php-gds": "1.2.1",

But I get the following error:

>>Problem 1
    - Installation request for tomwalder/php-gds 1.2.1 -> satisfiable by tomwalder/php-gds[v1.2.1].
    - tomwalder/php-gds v1.2.1 requires google/apiclient 1.1.3 -> no matching package found.

I'm not quite sure what to do and my entire site is dead broken. I'd be very appreciative if you could fill me in on the details to get it back up and running again.

**Comment by tomwalder** [comment]
Hey there.

I set up an application with the following composer.json, and everything worked just fine...

```json
{
    "require": {
        "tomwalder/php-gds": "1.2.1",
        "google/apiclient": "1.1.3"
    }
}
```

Does that help?

**Comment by bgold0** [comment]
Yup this works. Thanks Tom. I saw in the description to update to 1.1.4 so I had originally had 1.1.4 in there.
