### ISSUE TITLE
Question: There is way to test a repository using php-gds objects on GAE dev sdk?

### ISSUE THREAD

**Issue by muratsplat** [tomwalder/php-gds#64]
Example: 

```php

class GoogleDataStoregeTest extends TestCase
{
    
    
    public function testFirst()
    {
        
        // Build a new entity
            $obj_book = new GDS\Entity();
            $obj_book->title = 'Romeo and Juliet';
            $obj_book->author = 'William Shakespeare';
            $obj_book->isbn = '1840224339';

            // Write it to Datastore
            $obj_store = new GDS\Store('Book');// Exception: Could not determine DATASET, please pass to GDS\Gateway\ProtoBuf::__construct()

            $obj_store->upsert($obj_book);
        
    }
    
}

```
I have to repository class and this class will use Google Data Store.  Now I'm confusing about testing repository on gae development sdk...

**Comment by tomwalder** [comment]
You can pass in the dataset id.  Normally this is determined from the $_SERVER array when running in an App Engine environment - local or remote.

Not sure if this answers your questions?

**Comment by muratsplat** [comment]
Thank  you for the reply..

I think that GAE php  support and documentation is insufficient and poor. I don't mention  your library..

I have decided to develop my app using Golang..  I think that it is not suitable to use php on GAE... Google should work on php support of GAE  much more..
