### ISSUE TITLE
How do I define the key for a schema?

### ISSUE THREAD

**Issue by atrauzzi** [tomwalder/php-gds#65]
When I'm declaring a new schema, what's the correct way to describe what fields will comprise the key, or what the key is?

**Comment by tomwalder** [comment]
Datastore Entities have a ancestry key structure.

For any Entity without a "parent" (I tend to find this is most entities whilst you are getting going) the key is either 

`Namespace > Kind > KeyID`
or
`Namespace > Kind > KeyName`

Most of this is hidden away until you need it. So, you can create an Entity without specifying a key and the Datastore will assign an ID automatically for you.

for example

```php
$obj_book = $obj_store->createEntity(['title' => 'Romeo & Juilet']);
$obj_store->upsert($obj_book);

echo $obj_book->getKeyId();
```

Does this answer your question?

**Comment by tomwalder** [comment]
To complete that last message - if your Entity has a Parent (maybe Author on my example)

A key might be like this

`Namespace > [Author] > KeyID > [Book] > KeyID`

**Comment by atrauzzi** [comment]
Ah, this makes sense, okay.  Sorry, the GCD documentation is pretty good I think once the concepts are understood.  But I'm still picking things up.  (just coming back to learning GCD after having to take a break).

Thanks for your help in learning some of this :)

**Comment by atrauzzi** [comment]
@tomwalder Probably asking a bit much (I'm sure you're a busy guy), but do you use gitter.im at all?  Was wondering if I could ask you one or two more questions.

**Comment by tomwalder** [comment]
Just signed in to gitter.
