### ISSUE TITLE
Allow `$arr_data` to be fetched

### ISSUE THREAD

**Issue by atrauzzi** [tomwalder/php-gds#67]
I'm working on a scenario where I'd like `$arr_data` to be readable so that I can inspect the keys.  Unfortunately, right now, even if I wanted to make that possible in my subclass of `Entity`, I can't because it's marked as `private`.

Any chance there could either be a `getData` method or that the property could be changed to `protected` visibility?

**Comment by tomwalder** [comment]
Err... like this?

https://github.com/tomwalder/php-gds/blob/master/src/GDS/Entity.php#L177

**Comment by atrauzzi** [comment]
K, I get one derp today.

I was looking at my code assist popup and didn't see the method.  Sorry!

**Comment by tomwalder** [comment]
Ha, no problemo!
