### ISSUE TITLE
Grabbing id from fetchOne()

### ISSUE THREAD

**Issue by bgold0** [tomwalder/php-gds#7]
I'd like to thank you Tom, once again, for such an amazing library. I am trying to access the Google generated id from a datastore grab.

This is a `var_dump()` from a `fetchOne()` request:

    object(GDS\Entity)#16 (5)
    {
		["str_kind":"GDS\Entity":private]=>
			string(13) "User Sessions" ["str_key_id":"GDS\Entity":private]=>
				string(16) "5649391675244544" ["str_key_name":"GDS\Entity":private]=>
					NULL ["mix_ancestry":"GDS\Entity":private]=>
						NULL ["arr_data":"GDS\Entity":private]=>
							array(1) {
								["session_id"]=> string(3) "123"
							}
	}

I know if I wanted to get the `session_id` and this object was stored in `$object` I would just do `$object->session_id`

But I am trying to get the `str_key_id (5649391675244544)` but I can't figure out how to access it.

Could anyone help me figure it out?

**Comment by bgold0** [comment]
Sorry, I found the answer in the examples. Maybe this will help someone else.

`$object->getKeyId();`

**Comment by tomwalder** [comment]
Glad you got it sorted!
