### ISSUE TITLE
Dev GQL Parser

### ISSUE THREAD

**Issue by mpresland** [tomwalder/php-gds#70]
I have been working on a project using php-gds, and today transitioned to the proto-buffers to make local development a bit easier. This meant that my local datastore transactions have to go through your basic ProtoBufGQLParser.php that worked great until I added a condition to a query InstructionSet = @InstructionSet. I got an error : Unsupported operator in condition: [In] [ InstructionSet = @InstructionSet ] 
After scratching my head for a second, I realised as you have only made a basic GQL parser you were flagging unsupported operators, in my case you were picking up "IN" at the start of my field named "InstructionSet". I thought I should let you know, as anyone trying to work on the local dev with the proto buffers may run into the same issue when naming fields starting with 'in...' to resolve locally, I simply added a space in your $str_regex = '/(?<lhs>[^\s<>=]*)\s*(?<comp>=|<|<=|>|>=|IN |CONTAINS|HAS ANCESTOR|HAS DESCENDANT)\s*(?<rhs>[^\s<>=]+)/i'; on line 300 of ProtoBufGQLParser.php

I am fairly new to the GAE and datastore environment, and could not have done it without php-gds! Thanks for the hard work.

**Comment by tomwalder** [comment]
Hey there. Thanks for the spot.

I'll review and make a patch

**Comment by tomwalder** [comment]
FYI - from my testing, it appeared this was only manifesting where multiple WHERE clauses where applied.

Let me know if it fixes the issue for you - my tests are good!

**Comment by mpresland** [comment]
Thanks Tom! I will update and test when I get a chance. My query that raised the issue was indeed using multiple WHERE conditions. 

Thanks again for sharing php-gds, it has made life much easier!
