### ISSUE TITLE
How to use GDS crossing Apps?

### ISSUE THREAD

**Issue by gonejack** [tomwalder/php-gds#73]
I just make a app using php-gds, thank you author!

And I can't find a way from wiki or source code to share dataStore between apps,

Are there a method or class make for this purpose?

**Comment by tomwalder** [comment]
Datastore only provides "direct" access (using the faster Protocol Buffer API) for the app under which it was created.

However, you can access a Datastore from anywhere using the Google API (JSON over HTTP) from anywhere - as long as you have the right credentials file.
