### ISSUE TITLE
Key path element name is reserved when using __xyz__ as key for entity

### ISSUE THREAD

**Issue by xcodewarrier** [tomwalder/php-gds#74]
Hello,

Using the PHP-GDS library, I receive an exception when trying to 'upsert' an Entity when the key is in the format "\_\_xyz\_\_".

Is there a way to work around this, as the key is a username which I may have no control over, and \_\_xyz\_\_ is a perfectly valid username. Here's the code and the exception message:

    $username  =  "__xyz__";

    $obj_user = new Entity();
    $obj_user->setKeyName($username);
    try {
      $result = $obj_user_store->upsert($obj_user);
    }catch (Exception $e) {
       echo 'Caught exception: ',  $e->getMessage(), "\n";
       return false;
    }

    Caught exception: The key path element name "__xyz__" is reserved.

**Comment by tomwalder** [comment]
It looks like that exception is coming from Google / Datastore itself.

https://cloud.google.com/datastore/docs/apis/v1beta2/key

They state that `__.*__` is reserved

**Comment by xcodewarrier** [comment]
Hmm thats quite annoying as this is coming from a Twitter user - could this be 'datastore' encoded somehow by replacing the first/last two underscores?

**Comment by tomwalder** [comment]
I think you just need to try prefixing or something...

On 6 December 2015 at 18:53, xcodewarrier <notifications@github.com> wrote:

> Hmm thats quite annoying as this is coming from a Twitter user - could
> this be 'datastore' encoded somehow by replacing the first/last two
> underscores?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/74#issuecomment-162336732>.
>



-- 
*Tom Walder*, CTO *We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0845 521 0444 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This
message is private and confidential. If you have received this message in
error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by tomwalder** [comment]
Any luck?
