### ISSUE TITLE
Showcase of apps using php-gds

### ISSUE THREAD

**Issue by xcodewarrier** [tomwalder/php-gds#75]
Hi Tom,

Have you considered creating a showcase of apps that use php-gds? I'm sure it would be interesting to the wider community (and Google!) so see creative uses for the library.

**Comment by tomwalder** [comment]
I have not! Feel free to start one in this thread though ;-)

Most of mine are commercial, so can't really be posted here.

**Comment by tomwalder** [comment]
I'll reopen this if anyone is bothered... but for now
