### ISSUE TITLE
How to implement DataStore Indexes in Compute Engine (or Remote)?

### ISSUE THREAD

**Issue by clintcan** [tomwalder/php-gds#77]
Hi,
I really like the way this library implements the datastore - really easy.  However, I came across an issue which got me stumped (running this in compute engine not app engine so I use the JSON API).  I try calling  query that looks something like this:
SELECT * FROM <table> WHERE <field> = 'value' ORDER BY <field2>

But it returns a no index found error.  Running the query in the developer's console returns an error:
GQL query error: Your Datastore does not have the composite index (developer-supplied) required for this query. 

Looking into it more, documentation states you should create a datastore index configuration file - but that looks more like for App Engine or for the development server.  I'd really like to run this in the compute engine though.  Is there any way to do this?

For reference: https://cloud.google.com/datastore/docs/tools/indexconfig

**Comment by tomwalder** [comment]
Yes, you can use this from Compute Engine.

You still need to define the composite indexes either in the Google Developer Console - or by using the admin tools supplied by Google to upload an index.yaml file.

The Datastore itself will always run "in the cloud" somewhere - but this client library (php-gds) will run anywhere, including Compute Engine.

**Comment by clintcan** [comment]
I have defined index.yaml already and it's seen in the indexes of the google datastore.  It still returns an error.

In my index.yaml, it has this structure:
indexes:
- kind: testmsg
  properties:
  - name: from
  - name: message_id
  - name: room
  - name: create_date
    direction: desc

Error is: Uncaught exception 'Google_Service_Exception' with message 'Error calling POST https://www.googleapis.com/datastore/v1beta2/datasets/shopstyx/runQuery: (412) no matching index found.' 

Using query sample: SELECT * FROM testmsg WHERE room = '<room>' ORDER BY create_date

**Comment by tomwalder** [comment]
So you need a composite index on
* room
* create_date

(and only on those 2 fields).

If that still does not work, check your Schema definition to make sure you are not turning off indexing by passing false into the `addString` or `addDatetime` methods

**Comment by clintcan** [comment]
Thanks tom for helping out.  Anyways, that's the gist.  I didn't turn off indexing at all for those two properties.
