### ISSUE TITLE
Wrong Order of arguments in example file

### ISSUE THREAD

**Issue by kafcom** [tomwalder/php-gds#78]
Hi Tom, 

You might want to correct the order of arguments in the file **php-gds/examples/list_fetch.php** on **line 21**.
```php
// Configure the Store
$obj_store = new GDS\Store($obj_gateway, $obj_contact_schema);
```
It should be schema first then gateway but the reverse is the case in current example and throws a **Catchable fatal error**.

**Comment by tomwalder** [comment]
Hey there.

Thanks for the spot - I'll patch it ASAP.

I'm mid way through reworking all the examples which is, I suspect, why
this is old v1 code.

Cheers again

Tom

On Tuesday, 22 December 2015, kafcom <notifications@github.com> wrote:

> Hi Tom,
>
> You might want to correct the order of arguments in the file
> *php-gds/examples/list_fetchphp* on *line 21*
>
> // Configure the Store$obj_store = new GDS\Store($obj_gateway, $obj_contact_schema);
>
> It should be schema first then gateway but the reverse is the case in
> current example and throws a *Catchable fatal error*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/78>.
>


-- 
*Tom Walder*, CTO *We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This
message is private and confidential. If you have received this message in
error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA
