### ISSUE TITLE
Basic setup: APP_NAME and SERVICE_ACCOUNT_NAME

### ISSUE THREAD

**Issue by benuri** [tomwalder/php-gds#79]
What should be the values in config.php for GDS_APP_NAME and GDS_SERVICE_ACCOUNT_NAME?
I mean, where do I find these values in my Google cloud account?
Thanks!

define('GDS_APP_NAME', '');
define('GDS_KEY_FILE_PATH', $filename);
define('GDS_SERVICE_ACCOUNT_NAME', '');
define('GDS_DATASET_ID', '');

**Comment by tomwalder** [comment]
If you are using the "remote" JSON API, it is recommended to use the JSON service file. Example here:
https://github.com/tomwalder/php-gds/blob/master/examples/simple/create_one.php#L13

If you are planning to write an application to run directly on App Engine, then you should not need the above credentials - it's all automatic.

**Comment by benuri** [comment]
Thanks, it's working now!
