### ISSUE TITLE
Retrieving generated ID after upsert()

### ISSUE THREAD

**Issue by bgold0** [tomwalder/php-gds#8]
This is my code once I preform an upsert(). Is there a way to retrieve the generated ID that Google makes? I took a look at your examples and I see that you use a `var_dump()` often. However, when I do it, it returns `null`.

    $something = $obj_store->upsert($obj_store->createEntity(['something' => '123]));
    var_dump($something) //returns null

p.s. If there is a more appropriate place to post general questions and not really "issues", please let me know. And again, thank you for your help.

**Comment by tomwalder** [comment]
Hi there.

The trouble with your example is that you have lost the reference to the Entity object you created. Try this instead:

```php
$something = $obj_store->createEntity(['something' => '123']);
$obj_store->upsert($something);
var_dump($something->getKeyId());
```

**Comment by tomwalder** [comment]
In other words, the `upsert()` method does NOT return the Entity (because, for example, you might be working on an array of 100 Entities).

**Comment by bgold0** [comment]
You rock! This makes a lot more sense.
