### ISSUE TITLE
Updating existing schemas (that are in use)?

### ISSUE THREAD

**Issue by ajck** [tomwalder/php-gds#80]
At the suggestion of Tom, posting this as an issue, though not sure if it is or not :)

Just wondering how to handle updating existing schemas (that are in use) with php-gds. I wondered whether the example reindex.php script would be good to adapt. However, I also found this: https://cloud.google.com/appengine/articles/update_schema which talks about using task queues (and the API for that) because "if you need to update more than a couple thousand entities, you'll likely need to work around the short request deadline.". I am hoping there is a simpler way with php-gds though (ideally that doesn't need task queues as they look complex to implement) - and the reindex script doesn't cater for short request deadlines I guess (or does it internally?).

Many thanks

**Comment by tomwalder** [comment]
Hey.

The reason that article references tasks is that it is intended to run directly on App Engine.

With PHP-GDS, you can run software remotely too, using the JSON API / Gateway.

If you do that, you can run a script from your local machine/VM/whatever that runs forever. Probably not a terrible idea if you want to re-index a bunch of Entities.

Certainly, the `reindex.php` script was intended for this purpose.

Good luck!

**Comment by ajck** [comment]
@tomwalder thanks, that helps. I'm just trying to get my head around exactly how I do this (sorry, newbie to Datastore :) ). Say I wanted to add a couple of properties and remove a couple of properties in my schema which was now out there live in Datastore with e.g. a few million entities. I could take the reindex.php script which looks good as-is for this purpose, but then modify the boilerplate.php file I guess - so I'd edit the model schema removing the unwanted fields and adding in the new ones.

Is that enough? - or (in reindex.php) do I have to explicitly delete each entity before I upsert() it again? I don't want any entities with the old schema floating around in Datastore.

Also, if I am running on my local machine, does the live production Datastore get used automatically if I put in my service account details (in boilerplate.php), rather than the local dev server?

Also, can I avoid any write limits of Datastore (e.g. the 1 per second) - what's the most efficient/low cost way of doing this update (over millions of entities) - you say in the docs "I suggest paging your results if you need more than 1,000 records using fetchPage()." - so can I do e.g. fetchPage(10000) ? Is there a batch-write (or batch-update) equivalent to fetchPage?

Is this safe to do on a live production site do you think or is enforced site downtime required while the update is done?

Many thanks!
Alex

**Comment by tomwalder** [comment]
There are a lot of questions here... I will try and answer them all... but I might spread it out over a few comments.

## Batch Upserts ##

The `upsert()` method takes arrays of Entity objects. I tend to do 50 at a time. This is much more efficient than doing them one at a time.

## Upsert Replaces ##

When you `upsert()` an Entity, you are replacing the whole entity. Only fields present in the new object are sent and stored. Missing fields will disappear.

**Comment by tomwalder** [comment]
Here is some sample code (No warranty!)

```php
// We'll need a Google_Client, use our convenience method
$obj_client = GDS\Gateway\GoogleAPIClient::createClientFromJson('/some/file.json');

// Gateway requires a Google_Client and Dataset ID
$obj_gateway = new GDS\Gateway\GoogleAPIClient($obj_client, 'DATASET');

// Define our OLD Model Schema
$obj_book_schema = (new GDS\Schema('Book'))->addString('title')->addString('author');
$obj_book_store = new GDS\Store($obj_book_schema, $obj_gateway);

// Define our NEW Model Schema
$obj_book_schema2 = (new GDS\Schema('Book'))->addString('name')->addString('author');
$obj_book_store2 = new GDS\Store($obj_book_schema2, $obj_gateway);

// Fetch paginated, using the default query
while($arr_page = $obj_book_store->fetchPage(50)) {
    echo "Page contains ", count($arr_page), " records, upsert-ing (re-indexing)", PHP_EOL;
    $arr_new_books = [];
    foreach($arr_page as $obj_old_book) {
        $obj_new_book = $obj_book_store2->createEntity();
        $obj_new_book->name = $obj_old_book->title;
        $obj_new_book->author = $obj_old_book->author;
        $obj_new_book->setKeyId($obj_old_book->getKeyId());
        $arr_new_books[] = $obj_new_book;
    }
    $obj_book_store2->upsert($arr_new_books);
    echo "Upsert complete, attempting to fetch next page", PHP_EOL;
}
echo "No more data, complete.", PHP_EOL;
```

**Comment by ajck** [comment]
@tomwalder Thank you very much for the replies and the sample code, really helpful and I think solves the issue! Much appreciated.
