### ISSUE TITLE
Counting results

### ISSUE THREAD

**Issue by thedanielforum** [tomwalder/php-gds#83]
What would be the best approach for running count queries?
I have been searching for this and have problems finding a efficient approach.

I would highly appreciate any input!

**Comment by tomwalder** [comment]
There is no **really** efficient way to do this.

But if you are going to page through the results, then certainly you should use cursors (which this library does).

If you need to maintain a count, you should do it in your application (e.g. have a transaction increment/decrement layer)

**Comment by tomwalder** [comment]
Closing this issue, please re-open if needed.
