### ISSUE TITLE
$this->setEntityClass throwing error

### ISSUE THREAD

**Issue by mathewparet** [tomwalder/php-gds#84]
I am getting the below error when trying to extend the store class:

Fatal error: Call to a member function setEntityClass() on a non-object.

Code:

```
namespace glibix;

	use GDS;

	class source_store extends GDS\Store {

		protected function buildSchema() {

			$this->setEntityClass('\\glibix\source');
			return (new GDS\Schema('Sources'))
				->addString('english_name')
				->addString('unicode_name')
				->addDatetime('created')
				->addDatetime('modified')
				->addBoolean('disabled')
				->addString('feed_url')
				->addString('site_url');
		}

		function upsert($entities) {
			if(!is_array($entities))
				$entities=[$entities];
			foreach ($entities as $entity) 
				$entity->modified=date('Y-m-d H:i:s');
			parent::upsert($entities);
		}

	}
```

**Comment by tomwalder** [comment]
The example is out of date I'm afraid.

The `Schema` has to exist before you can change the `Entity` class through the `Store`.

However, **you can set the Entity class directly on the `Schema` when you are building it**. The method is the same.

https://github.com/tomwalder/php-gds/blob/master/src/GDS/Schema.php#L193

**Comment by mathewparet** [comment]
Thanks Tom

**Comment by tomwalder** [comment]
Closing this for now. please re-open if needed.
