### ISSUE TITLE
Autoload file not found

### ISSUE THREAD

**Issue by sathishmoo** [tomwalder/php-gds#85]
I have  tried with this code but i'm getting 500 internal error and autoload file not found error also coming

**Comment by tomwalder** [comment]
Sorry, that's not really enough information for me to help.

Are you using Composer?

The library works well for many people, so I expect it's an issue at your end...

**Comment by sathishmoo** [comment]
Very thanks for your reply Mr.tomwalder , 

I have Completed all the process  so now its working fine .
I can able to do all the process. So we can close this thread.
