### ISSUE TITLE
Working with keys

### ISSUE THREAD

**Issue by ajck** [tomwalder/php-gds#86]
Just trying to understand Datastore keys in the context of php-gds. I was planning to create a unique alphanumeric 10 character ID as the key for each entity in my store, but on second thoughts I'm thinking the auto generated numeric ID will suffice and is perfectly secure (i.e. generating my own one offers no extra security)? From a php-gds perspective I assume making my own keys would affect pagination?

I was looking for info on key related functions in php-gds, and I found a couple in the examples code (setkeyname and setkeyid) but it made me think is there a full API list for php-gds anywhere listing all available functions and what they do? (I'm not sure if some of the functions in the examples code are not part of the public API, or are instead part of Google's Datastore API).

Many thanks

**Comment by tomwalder** [comment]
IDs offer no kind of "security" - they are just numbers. The numeric IDs generated by Datastore are somewhat random 64-bit integers.

Keys will only affect pagination if you "sort by key".. I guess.

The README is a good place to start for documentation
https://github.com/tomwalder/php-gds/blob/master/README.md

Then the public methods exposed on the `GDS\Store` class

**Comment by tomwalder** [comment]
Closing this issue - please reopen if needed.

**Comment by ajck** [comment]
Thanks for your help Tom. I wasn't sure if keys were stable and could be relied upon to be unchanging (e.g. over time, during entity updates etc) so they can be used as a reference in other entities - do you happen to know if this is the case?

**Comment by tomwalder** [comment]
Yes, keys are unchanging - unless YOU change them ;-o

On 11 February 2016 at 14:41, ajck <notifications@github.com> wrote:

> Thanks for your help Tom. I wasn't sure if keys were stable and could be
> relied upon to be unchanging (e.g. over time, during entity updates etc) so
> they can be used as a reference in other entities - do you happen to know
> if this is the case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/86#issuecomment-182892400>.
>



-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA
