### ISSUE TITLE
Missing property's = Text, GeoPt

### ISSUE THREAD

**Issue by troykelly** [tomwalder/php-gds#87]
I'm trying to store some arrays of data, and location information.

I can't find an [addText](https://cloud.google.com/appengine/docs/python/datastore/typesandpropertyclasses#TextProperty) or [addGeoPt](https://cloud.google.com/appengine/docs/python/datastore/typesandpropertyclasses#GeoPtProperty) method - at the moment we are just storing the serialised data in String's - but we will start running into issues as a string can only be 1500 bytes or less.

**Comment by tomwalder** [comment]
For long text properties, use `addString()` but make sure you turn off INDEXING

`->addString('long_text', false)`

Text fields can only index up to 1500 bytes.

**Comment by tomwalder** [comment]
GeoPoint types are not yet supported.

**Comment by troykelly** [comment]
Thank you for clarifying

**Comment by tomwalder** [comment]
I have added support for Geopoint support in the latest development branch
