### ISSUE TITLE
fetchById not working

### ISSUE THREAD

**Issue by mathewparet** [tomwalder/php-gds#88]
I was trying to fetch an entity by id, but its failing. The data I have in store looks like this:
![screen shot 2016-02-08 at 10 33 16 pm](https://cloud.githubusercontent.com/assets/2384106/12892889/3e0b3102-ceb4-11e5-87d1-8e3f278fde10.png)

My code trying to retrieve the data is:
```php
if(isset($_GET['sub_id']) && $_GET['sub_id']) {
		$subscription = (new GDS\Store('Subscriptions'))->fetchById($_GET['sub_id']);
		var_dump($subscription);
	}
```

I call the script using the $_GET param sub_id=5717271485874176 but nothing is returned. All I get is NULL.

**Comment by tomwalder** [comment]
So, there are a couple of reasons why this might be the case.

1. Your data is in another "namespace"
2. Your entity is not a root entity (i.e. is has an ancestor entity). `fetchById` and `fetchByName` only work on root entities.

**Comment by tomwalder** [comment]
Closing this issue. Please re-open if needed.

**Comment by lifeofguenter** [comment]
So it's not possible to get an entity over it's id if it is not root?

**Comment by tomwalder** [comment]
It is possible - but you would have to craft the GQL query yourself to use
the full ancestor path.

I'm away at the moment but can post an example when I get back to a machine.

Tom

On Saturday, 9 July 2016, Gunter Grodotzki <notifications@github.com> wrote:

> So it's not possible to get an entity over it's id if it is not root?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/88#issuecomment-231546223>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABMyk5lNS8bll0axqaSgfE0GQNj2garkks5qT9zBgaJpZM4HVs4->
> .
>


-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA
