### ISSUE TITLE
Unsure how to commit

### ISSUE THREAD

**Issue by troykelly** [tomwalder/php-gds#89]
I'm upserting new data, and then sometimes have need to modify that data.

It doesn't seem to exist immediately, so I assume that it's being held in a transaction.

Is there some way to commit an "upsert" so that the data is immediately available?

**Comment by tomwalder** [comment]
Simple answer, "no".

Datastore has distributed geographic replication. Once side effect of this is something called "Eventual Consistency" - which does mean that, from time to time, Entities will not be available immediately after insertion.

Personally, I have never experienced this and it has always been available straight away.

If you run a "fetch" against a Key (name or id) then you should always get the data back straight away, because the query is "deterministic".

The library DOES support transactions - but I do not think that will not help you here.

**Comment by troykelly** [comment]
Thank you for that. I'm going to have to hand objects around I think, and update them that way.

I have code that inserts a record, and then sometimes nearly immediately after needs to update it with some additional information. The inserted information is _never_ available in this circumstance. If I task however, it's available so a newly called task (eg task1 inserts and instantiates task2 which looks it up)

The problem I have is such:
.code.
.code.
  $object->upsert(...);
.code.
.code.
 $thing = functionThatNeedsTheData(); //Data is not there

**Comment by tomwalder** [comment]
If the process you are describing is in a single thread of execution then
retrieving again from Datastore is inefficient anyway.

So, retaining a reference to the created entities is a good plan.

You could also consider a Unit Of Work style pattern where the entities are
only inserted once at the end of the execution cycle.



On Tuesday, 9 February 2016, Troy Kelly <notifications@github.com> wrote:

> Thank you for that. I'm going to have to hand objects around I think, and
> update them that way.
>
> I have code that inserts a record, and then sometimes nearly immediately
> after needs to update it with some additional information. The inserted
> information is *never* available in this circumstance. If I task however,
> it's available so a newly called task (eg task1 inserts and instantiates
> task2 which looks it up)
>
> The problem I have is such:
> .code.
> .code.
> $object->upsert(...);
> .code.
> .code.
> $thing = functionThatNeedsTheData(); //Data is not there
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/89#issuecomment-181756406>.
>


-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by troykelly** [comment]
I was trying to be lazy - there are six parts to this and they all exist in their own classes doing their own thing. They hand data back and forth, and some of them for a task to do more things.

You are completely correct - I need to shift to a Unit Of Work design pattern, and move the database and task triggering to the end.
