### ISSUE TITLE
fetchAll() error when grabbing from Kind with spaces

### ISSUE THREAD

**Issue by bgold0** [tomwalder/php-gds#9]
I may be going about this totally wrong. So if I am I apologize.

Here is my error:
> Fatal error: Uncaught exception 'Google_Service_Exception' with message 'Error calling POST https://www.googleapis.com/datastore/v1beta2/datasets/nice-virtue-798/runQuery: (400) Encountered "Something" at line 1, column 20. Was expecting one of: <EOF> "group" ... "limit" ... "offset" ... "order" ... "where" ... '

This only happens when I do a `fetchAll()` command on a KIND with two words. This doesn't happen when I do a SELECT query or anything like that.

    //doesn't work
    $obj_store = new GDS\Store($obj_gateway, "Something Space");
    $something = $obj_store->fetchAll();
    
    //works
    $obj_store = new GDS\Store($obj_gateway, "Something Space");
    $something = $obj_store->fetchAll("SELECT * FROM `Something Space`");

    //also works
    $obj_store = new GDS\Store($obj_gateway, "Something");

Should I not be having KIND's with spaces? If KIND's with spaces aren't the best practice, I won't do it. But I'd like to use them if I can.

**Comment by bgold0** [comment]
Also, whenever you get around to looking at this, you have a lot of examples on how to cycle through all of these items from a `fetchAll()`, but I am curious on how I would target one specific item once I know the ID that I want to grab.

So for example, after a `fetchAll()`, my `$something` would look something like:

    Array ( 
		[0] => GDS\Entity Object (
			[str_kind:GDS\Entity:private] => Item List
			[str_key_id:GDS\Entity:private] => 5659313586569216
			[str_key_name:GDS\Entity:private] => 
			[mix_ancestry:GDS\Entity:private] => 
			[arr_data:GDS\Entity:private] => Array ( [item] => 123 )
		)

		[1] => GDS\Entity Object (
			[str_kind:GDS\Entity:private] => Item List
			[str_key_id:GDS\Entity:private] => 5722646637445120
			[str_key_name:GDS\Entity:private] =>
			[mix_ancestry:GDS\Entity:private] =>
			[arr_data:GDS\Entity:private] => Array ( [item] => 456 )
		)
	)

If I wanted to grab the data/array from `5659313586569216`, what would the appropriate method of doing that?

**Comment by tomwalder** [comment]
So, your second comment is just a case of using `fetchById()`

```php
$obj_result = $obj_store->fetchById(5659313586569216);
```

**Comment by tomwalder** [comment]
Your first comment highlights a bug in the software - I am not encapsulating Kind names in the Default Query.

I'll fix this and deploy an update.

**Comment by bgold0** [comment]
So about the:

    $obj_result = $obj_store->fetchById(5659313586569216);

The reason why I was fetching all first is because I want to fetch hundreds of items, and then call for that data multiple times.

Wouldn't it be more efficient to fetchAll in one Datastore command and then cycle through and grab what is needed in the array then make a hundred calls to the Datastore?

To be more efficient, I was going to do a `foreach` and put it in an array but I was wondering if there was an easier way.

**Comment by tomwalder** [comment]
If you want an array keyed on the Datstore auto insert Id, like this:

`$arr[<datastore-key-id>] = $entity;`

Then what you have done is fine - a single call to Datastore then re-arrage the array to be keyed by Id.

BUT, the reason this sort of function is not built into `php-gds` is that Entities are not guaranteed to have a Key Id. Some entities may use Key Name instead.

But, if yo know in your application you are going to use IDs all the time, what you have is fine.
