### ISSUE TITLE
Pulling records from datastore..

### ISSUE THREAD

**Issue by sathishmoo** [tomwalder/php-gds#92]
Here im trying to get data from 100th row to 200 th row but i'm not ableto get the result can you help me please

**Comment by tomwalder** [comment]
Can you provide the code you are using?

**Comment by sathishmoo** [comment]
$GLOBALS['obj_book_store']->query("SELECT * FROM VideoTest ORDER BY LINK_TIME desc WHERE ROWNUM > 101 AND ROWNUM < 200");

**Comment by sathishmoo** [comment]
$GLOBALS['obj_book_store']->fetchAll("SELECT * FROM VideoTest ORDER BY LINK_TIME desc WHERE ROWNUM > 101 AND ROWNUM < 200");

**Comment by tomwalder** [comment]
What are your index definitions?

**Comment by sathishmoo** [comment]
LINK_TIME is index only

**Comment by tomwalder** [comment]
You will need an index on each property in your WHERE clause.

And in you are going to SORT as well, you may need a composite index.



On Tuesday, 16 February 2016, sathish kamaraj <notifications@github.com>
wrote:

> LINK_TIME is index only
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/92#issuecomment-184508772>.
>


-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by sathishmoo** [comment]
Thanks Tomwalder,
