### ISSUE TITLE
Storing image/binary/blob data?

### ISSUE THREAD

**Issue by ajck** [tomwalder/php-gds#93]
Hi,
I want to store image data for large thumbnails (e.g. 200 X 200 px or smaller) in my user entities in datastore (unless this is a bad idea for some reason?). Just wondering what the best way of doing this with php-gds might be? Am I right in thinking it doesn't support blobs? How about binary strings?

I was thinking the safest (only?) way was to base64 encode the image data then stick it in a string property (not indexed). Are there any length, encoding, or other limitations I should be aware of?

Many thanks!
Alex

**Comment by tomwalder** [comment]
Base64 is your best option at the moment.

1MB limit on non-indexed strings.

Perhaps suffix the field with "_b64" or something so it's easier to
refactor out later.

The other option is to store the binary files on cloud storage with the
gs:/ stream wrapper

On Monday, 15 February 2016, ajck <notifications@github.com> wrote:

> Hi,
> I want to store image data for large thumbnails (e.g. 200 X 200 px or
> smaller) in my user entities in datastore (unless this is a bad idea for
> some reason?). Just wondering what the best way of doing this with php-gds
> might be? Am I right in thinking it doesn't support blobs? How about binary
> strings?
>
> I was thinking the safest (only?) way was to base64 encode the image data
> then stick it in a string property (not indexed). Are there any length,
> encoding, or other limitations I should be aware of?
>
> Many thanks!
> Alex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/93>.
>


-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by ajck** [comment]
Great thanks Tom, I'll use Base64
