### ISSUE TITLE
Unsupported SSL context options are set

### ISSUE THREAD

**Issue by sathishmoo** [tomwalder/php-gds#94]
i'm getting this error  "Unsupported SSL context options are set. The following options are present, but have been ignored: cafile" in every request but giving success response.

**Comment by tomwalder** [comment]
Can you please provide more details on your environment?

Local or App Engine?
Mac/Windows/Linux?
Launcher or command line?

Anything else?

**Comment by sathishmoo** [comment]
This is happening in APP ENGINE , I have deployed from Ubuntu machine and i can see those errors is appengine log but in response , i'm getting proper data with success response.

**Comment by tomwalder** [comment]
Can you show me the code?

The system should be using protocol buffers on app engine usually and not
JSON API, so I'm unsure where the error is coming from

On Thursday, 18 February 2016, sathish kamaraj <notifications@github.com>
wrote:

> This is happening in APP ENGINE , I have deployed from Ubuntu machine and
> i can see those errors is appengine log but in response , i'm getting
> proper data with success response.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/94#issuecomment-185540822>.
>


-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by sathishmoo** [comment]
Actually i'm getting reaponse as a JSON , 

So, is it making an issue?

**Comment by tomwalder** [comment]
Fundamentally, it's likely that some "unsupported" options are being set on
the HTTP client. And then the URL fetch service from Google is bubbling up
an error.

Without seeing the code, I cant help much more.



On 18 February 2016 at 12:21, sathish kamaraj <notifications@github.com>
wrote:

> Actually i'm getting reaponse as a JSON ,
>
> So, is it making an issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/94#issuecomment-185694360>.
>



-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by tomwalder** [comment]
You should (usually) use the Protocol Buffer gateway on AppEngine and NOT the JSON version.

For performance reasons.
