### ISSUE TITLE
HAS Query

### ISSUE THREAD

**Issue by sathishmoo** [tomwalder/php-gds#95]
Hi Tom ,

I have tried to make query with HAS example but not able to understand ,Please can you help me 
$variavleValue=$_GET['searchText'];

"SELECT * FROM VideoTest where __key__ HAS NAME $variavleValue"

**Comment by tomwalder** [comment]
I do not think "HAS" is a stand-alone operator.

What example are you following (can you send me a link?)

What are you trying to do? I can suggest a query?

On 19 February 2016 at 10:45, sathish kamaraj <notifications@github.com>
wrote:

> Hi Tom ,
>
> I have tried to make query with HAS example but not able to understand
> ,Please can you help me
> $variavleValue=$_GET['searchText'];
>
> "SELECT * FROM VideoTest where *key* HAS NAME $variavleValue"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/95>.
>



-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by sathishmoo** [comment]
php-gds/examples/ancestor_key_lookups.php

If the string is found in the particular key column that data should come,

Like , mysql like query

$GLOBALS['obj_book_store']->fetchAll("SELECT * FROM VideoTest where __key__ HAS NAME $_GET['searchText']"); 

This is what i tried,

**Comment by tomwalder** [comment]
You should probably just use "=" rather than "HAS".

There is a "HAS ANCESTOR" operator from the sample, but it's not the same.

**Comment by sathishmoo** [comment]
Hi Tom Walder,

Please can you help me ,

I want retrieve the data with part of the string in particular key like (MYSQL LIKE clause).

Please give some example

**Comment by sathishmoo** [comment]
If i Use  "=" rather than "HAS" ,result set is empty because input string is part of the entire string of the key value , That's why i'm using HAS ANCESTOR.

**Comment by tomwalder** [comment]
Datastore does not have a "LIKE" operator.

You might consider using the Google Cloud Search API - here is a library
https://github.com/tomwalder/php-appengine-search

**Comment by sathishmoo** [comment]
HI tom,
Here anything required for datastore configuration?
if is there , Where you are mention  in this document

Just i'm working with pub search

**Comment by sathishmoo** [comment]
And one more question is , can i use directly this code inside the gds-php library

**Comment by tomwalder** [comment]
It's open source... do what you like with it ;-)

On 25 February 2016 at 06:53, sathish kamaraj <notifications@github.com>
wrote:

> And one more question is , can i use directly this code inside the gds-php
> library
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/95#issuecomment-188640700>.
>



-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by sathishmoo** [comment]
Thank You Tom.

**Comment by sathishmoo** [comment]
I'm not able to use search functionality here , Please , Can you guide me

**Comment by tomwalder** [comment]
Hi there,

I'm really sorry, but I don't have the time - the best I can offer you is
the 2 READMEs for the projects:

https://github.com/tomwalder/php-gds

https://github.com/tomwalder/php-appengine-search

And the Google Docs

https://cloud.google.com/appengine/training/fts_intro/

Tom

On 25 February 2016 at 10:14, sathish kamaraj <notifications@github.com>
wrote:

> I'm not able to use search functionality here , Please , Can you guide me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/95#issuecomment-188705753>.
>



-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA
