### ISSUE TITLE
Date comparison  while pulling

### ISSUE THREAD

**Issue by sathishmoo** [tomwalder/php-gds#97]
Hi I have to compare and pull data based on data

This is the code i'm using , can you help me here,
$requiredDate= date('d/m/Y h:i A', strtotime($date)) ;
              
$query="SELECT DISTINCT * FROM VideoTest where LINK_TIME < '".$requiredDate."' ORDER BY LINK_TIME desc LIMIT 20";

From this code , I'm getting result set but that is not correct data set because in this where condition is not working .

**Comment by tomwalder** [comment]
A better way to do this would be (using parameter binding and Datetime)

```php
$query = "SELECT DISTINCT * FROM VideoTest where LINK_TIME < @reqDate ORDER BY LINK_TIME desc";
$store->query($query, ['reqDate' => new Datetime('@'.strtotime($date))]);
$store->fetchPage(20);
```

P.S. I have not syntax checked this

**Comment by sathishmoo** [comment]
Thanks Tom ,

Again i'm facing one problem,
Always its giving same result set but input date is different

**Comment by tomwalder** [comment]
I'm going to have problems helping you without seeing your data... sorry!

On 3 March 2016 at 11:21, sathish kamaraj <notifications@github.com> wrote:

> Thanks Tom ,
>
> Again i'm facing one problem,
> Always its giving same result set but input date is different
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomwalder/php-gds/issues/97#issuecomment-191713636>.
>



-- 
*Tom Walder*, CTO
*We're hiring.* Find out more at www.docnet.nu/jobs
<http://www.docnet.nu/jobs?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
*Call*: 0161 660 7110 / *Web*: www.docnet.nu
<http://www.docnet.nu/?utm_source=email_signature&utm_medium=email&utm_campaign=email_signature>
This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Venditan Limited
t/a Docnet is a company registered in England and Wales. Registered number:
9604502. Registered office: Speakers House, 39 Deansgate, Manchester, M3 2BA

**Comment by sathishmoo** [comment]
function getmoreView(){
               // $obj_store = new GDS\Store($obj_gateway, 'CATEGORY');
                $query = "SELECT  * FROM VideoTest where LINK_TIME < @reqDate ORDER BY LINK_TIME desc";
                $arr_page= $GLOBALS['obj_book_store']->query($query, ['reqDate' => new Datetime('d/m/Y H:i A',strtotime($_GET['lastRecordDateForRecentVideos']))])->fetchPage(10);
                describeResult($arr_page);
            }

**Comment by tomwalder** [comment]
It's the data I need to see (and indexes) not the code (although the code is useful, thank you!
